.TH "OVERLAYS" "5" "January 10, 2021" "Tribblix"
.SH NAME
overlays - collections of installed packages
.SH DESCRIPTION
Tribblix uses the SVR4 packaging system to manage installed software
packages. However, this does not provide a very useful level of
abstraction, and it is recommended that users and administrators
manage installed software at a higher level, using overlays.
.LP
An \fBoverlay\fR is a group of packages that are installed together, that
provides a meaningful set of functionality. Overlays are managed using
the \fBzap\fR(1) utility.
.LP
To list the available overlays
.sp
.in +2
.nf
\fBzap\fR \fBlist-overlays\fR [\fB-u\fR|\fB-i\fR]
.fi
.in -2
.sp
.LP
To update the list of available overlays and catalog of available
packages from the network repository
.sp
.in +2
.nf
\fBzap\fR \fBrefresh\fR
.fi
.in -2
.sp
.LP
To install an overlay
.sp
.in +2
.nf
\fBzap\fR \fBinstall-overlay\fR \fIoverlay_name\fR
.fi
.in -2
.sp
.LP
To update all the packages in an overlay to their current versions
(or all overlays, with -a)
.sp
.in +2
.nf
\fBzap\fR \fBupdate-overlay\fR \fIoverlay_name\fR
.fi
.in -2
.sp
.LP
Overlays are also used as the unit of software management in zones of
the \fBwhole-root\fR(5) brand.
.SH FILES
The files defining overlays are stored in the \fB/var/sadm/overlays\fR
directory.
.SH SEE ALSO
\fBzap\fR(1), \fBwhole-root\fR(5)
