#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# simple wrapper to install locales
# just maps keywords to package names
# also adds hunspell dictionaries if we have them
#

ZAPLIBDIR="/usr/lib/zap"
CTXARGS=""
PKGARGS=""
ACTION="install-pkg"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	;;
esac

#
# use this wrapper for uninstall and list as well
# -d - uninstall the given locales
# -i - list installed locale packages and locales
# -l - list available locale packages
#
case $1 in
    -d)
	shift
	ACTION="delpkg"
	CTXARGS=""
	;;
    -i)
	shift
	cd "${DESTROOT}/var/sadm/pkg" || exit 1
	#
	# detect if there are no additional locales installed so we can
	# give a more useful message
	#
	for pkg in TRIBlocale-*
	do
	    if [ ! -d "$pkg" ]; then
		echo "No locale packages installed"
		exit 0
	    fi
	done
	echo "Installed locale packages:"
	/bin/ls -1d TRIBlocale-*
	#
	# the locale command isn't aware of alternate roots and would
	# print information for the current system, which is misleading
	#
	if [ -z "${DESTROOT}" ]; then
	    if [ -x /usr/bin/locale ]; then
		echo "Available locales:"
		/usr/bin/locale -a
	    fi
	fi
	exit 0
	;;
    -l)
	shift
	cd "${DESTROOT}/var/sadm/pkg" || exit
	if [ ! -f "${DESTROOT}/var/sadm/overlays/all-locales.pkgs" ]; then
	    echo "No locale availability present."
	    exit 1
	fi
	echo "Available locale packages:"
	for nlocale in $(<"${DESTROOT}/var/sadm/overlays/all-locales.pkgs")
	do
	    if [ -d "${nlocale}" ]; then
		echo "$nlocale (Installed)"
	    else
		echo "$nlocale"
	    fi
	done
	exit 0
	;;
esac

LPKGLIST=""
SPELLPKG=""

#
# now there's a big switch that maps names to packages
#
for arg in "$@"
do
    case $arg in
	af|afrikaans)
	    LPKGLIST="${LPKGLIST} af"
	    ;;
	ar|arab*)
	    LPKGLIST="${LPKGLIST} ar"
	    ;;
	as|assam*)
	    LPKGLIST="${LPKGLIST} as"
	    ;;
	az|azerbaijan*)
	    LPKGLIST="${LPKGLIST} az"
	    ;;
	be|belarus*)
	    LPKGLIST="${LPKGLIST} be"
	    ;;
	bg|bulgaria*)
	    LPKGLIST="${LPKGLIST} bg bg-extra"
	    ;;
	bn|bengal*)
	    LPKGLIST="${LPKGLIST} bn"
	    ;;
	bo|tibet*)
	    LPKGLIST="${LPKGLIST} bo"
	    ;;
	bs|bosnia*)
	    LPKGLIST="${LPKGLIST} bs"
	    ;;
	ca)
	    echo "Ambiguity for ca: please use catalan or canada"
	    exit 1
	    ;;
	canad*)
	    LPKGLIST="${LPKGLIST} en en-extra fr fr-extra"
	    SPELLPKG="${SPELLPKG} en fr"
	    ;;
	catalan*)
	    LPKGLIST="${LPKGLIST} ca ca-extra"
	    ;;
	cs|cz*)
	    LPKGLIST="${LPKGLIST} cs cs-extra"
	    ;;
	da|den*|danish)
	    LPKGLIST="${LPKGLIST} da da-extra"
	    ;;
	de|deu*|german*)
	    LPKGLIST="${LPKGLIST} de de-extra"
	    SPELLPKG="${SPELLPKG} de"
	    ;;
	el|gree*)
	    LPKGLIST="${LPKGLIST} el el-extra"
	    ;;
	en|engl*|brit*)
	    LPKGLIST="${LPKGLIST} en en-extra"
	    SPELLPKG="${SPELLPKG} en"
	    ;;
	es|esp*|spanish|spain)
	    LPKGLIST="${LPKGLIST} es es-extra"
	    ;;
	et|estonia*)
	    LPKGLIST="${LPKGLIST} et"
	    ;;
	fi|fin*)
	    LPKGLIST="${LPKGLIST} fi fi-extra"
	    ;;
	fil|filipon*|philipin*)
	    LPKGLIST="${LPKGLIST} fil"
	    ;;
	fr|french|france)
	    LPKGLIST="${LPKGLIST} fr fr-extra"
	    SPELLPKG="${SPELLPKG} fr"
	    ;;
	ga|irish|ireland|gaelic)
	    LPKGLIST="${LPKGLIST} ga"
	    ;;
	gu|gujarat*)
	    LPKGLIST="${LPKGLIST} gu"
	    ;;
	he|heb*)
	    LPKGLIST="${LPKGLIST} he"
	    ;;
	hi|hind*)
	    LPKGLIST="${LPKGLIST} hi"
	    ;;
	hr|croat*)
	    LPKGLIST="${LPKGLIST} hr hr-extra"
	    ;;
	hun|hungar*)
	    LPKGLIST="${LPKGLIST} hu hu-extra"
	    ;;
	hy|armenia*)
	    LPKGLIST="${LPKGLIST} hy"
	    ;;
	id|indonesia*)
	    LPKGLIST="${LPKGLIST} id"
	    ;;
	ii|yi)
	    LPKGLIST="${LPKGLIST} ii"
	    ;;
	is|iceland*)
	    LPKGLIST="${LPKGLIST} is is-extra"
	    ;;
	it|ital*)
	    LPKGLIST="${LPKGLIST} it it-extra"
	    SPELLPKG="${SPELLPKG} it"
	    ;;
	ja|jap*)
	    LPKGLIST="${LPKGLIST} ja"
	    ;;
	ka|georgia*)
	    LPKGLIST="${LPKGLIST} ka"
	    ;;
	kk|kazakh*)
	    LPKGLIST="${LPKGLIST} kk"
	    ;;
	km|khmer*)
	    LPKGLIST="${LPKGLIST} km"
	    ;;
	kn|kannada)
	    LPKGLIST="${LPKGLIST} kn"
	    ;;
	ko|korea*)
	    LPKGLIST="${LPKGLIST} ko"
	    ;;
	kok|konk*)
	    LPKGLIST="${LPKGLIST} kok"
	    ;;
	lt|lithuania*)
	    LPKGLIST="${LPKGLIST} lt lt-extra"
	    ;;
	lv|latvia*)
	    LPKGLIST="${LPKGLIST} lv lv-extra"
	    ;;
	mk|macedonia*)
	    LPKGLIST="${LPKGLIST} mk mk-extra"
	    ;;
	ml|malayalam)
	    LPKGLIST="${LPKGLIST} ml"
	    ;;
	mn|mongol*)
	    LPKGLIST="${LPKGLIST} ml"
	    ;;
	mr|marath*)
	    LPKGLIST="${LPKGLIST} mr"
	    ;;
	ms|malay*)
	    LPKGLIST="${LPKGLIST} ms"
	    ;;
	mt|malt*)
	    LPKGLIST="${LPKGLIST} mt"
	    ;;
	nb|bokmal)
	    LPKGLIST="${LPKGLIST} nb"
	    ;;
	ne|nepal*)
	    LPKGLIST="${LPKGLIST} ne"
	    ;;
	nl|holland|dutch|nederland*|netherland*)
	    LPKGLIST="${LPKGLIST} nl nl-extra"
	    ;;
	nn|nynorsk)
	    LPKGLIST="${LPKGLIST} nn"
	    ;;
	norw*|norge)
	    LPKGLIST="${LPKGLIST} nb nn"
	    ;;
	or|oriya)
	    LPKGLIST="${LPKGLIST} or"
	    ;;
	pa|punjab*)
	    LPKGLIST="${LPKGLIST} pa"
	    ;;
	pl|pol*)
	    LPKGLIST="${LPKGLIST} pl pl-extra"
	    ;;
	pt|port*)
	    LPKGLIST="${LPKGLIST} pt pt-extra"
	    ;;
	ro|romania*)
	    LPKGLIST="${LPKGLIST} ro"
	    ;;
	ru|russia*)
	    LPKGLIST="${LPKGLIST} ru ru-extra"
	    ;;
	sa|sanskrit)
	    LPKGLIST="${LPKGLIST} sa"
	    ;;
	si|sinhal*)
	    LPKGLIST="${LPKGLIST} si"
	    ;;
	sk|slovak*)
	    LPKGLIST="${LPKGLIST} sk"
	    ;;
	sl|slovenia*)
	    LPKGLIST="${LPKGLIST} sl"
	    ;;
	sq|albania*)
	    LPKGLIST="${LPKGLIST} sq sq-extra"
	    ;;
	sr|serb*)
	    LPKGLIST="${LPKGLIST} sr"
	    ;;
	sv|sver*|swed*)
	    LPKGLIST="${LPKGLIST} sv sv-extra"
	    ;;
	ta|tamil)
	    LPKGLIST="${LPKGLIST} ta"
	    ;;
	te|telugu)
	    LPKGLIST="${LPKGLIST} te"
	    ;;
	th|thai)
	    LPKGLIST="${LPKGLIST} th th-extra"
	    ;;
	tr|turk*)
	    LPKGLIST="${LPKGLIST} tr tr-extra"
	    ;;
	ug|uighur)
	    LPKGLIST="${LPKGLIST} ug"
	    ;;
	uk)
	    echo "Ambiguity for uk: please use english or ukrainian"
	    exit 1
	    ;;
	ukrain*)
	    LPKGLIST="${LPKGLIST} uk"
	    ;;
	ur|urdu)
	    LPKGLIST="${LPKGLIST} ur"
	    ;;
	vi|vietnam*)
	    LPKGLIST="${LPKGLIST} vi"
	    ;;
	zh_cn|china)
	    LPKGLIST="${LPKGLIST} zh_cn zh_cn-extra"
	    ;;
	zh_hk|hk|hongkong)
	    LPKGLIST="${LPKGLIST} zh_hk"
	    ;;
	zh_mo|macau)
	    LPKGLIST="${LPKGLIST} zh_mo"
	    ;;
	zh_sg|singapor*)
	    LPKGLIST="${LPKGLIST} zh_sg"
	    ;;
	zh_tw|taiwan*)
	    LPKGLIST="${LPKGLIST} zh_tw"
	    ;;
	*)
	    echo "Unrecognized name $arg"
	    exit 1
	    ;;
    esac
done

if [ -z "$LPKGLIST" ]; then
    exit 0
fi

PKGLIST=""
for lcl in $LPKGLIST
do
    PKGLIST="${PKGLIST} TRIBlocale-${lcl}"
done
for lcl in $SPELLPKG
do
    PKGLIST="${PKGLIST} TRIBspelldict-${lcl}"
done

exec ${ZAPLIBDIR}/${ACTION} ${CTXARGS} ${PKGARGS} $PKGLIST
