#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# verifies the contents of an installed package
#
# For now, use pkgchk. Later, should use a digitally signed package manifest
# with stronger checksums
#
# In the global zone, we use the individual package's pkgmap file
# else verify using the contents file. It's better to use the pkgmap
# as it will detect a file being modified by another package.
#

for pkg in "$@"
do
  if [ -d "/var/sadm/pkg/${pkg}" ]; then
    echo "Checking $pkg"
    if [ -f "/var/sadm/pkg/${pkg}/save/pspool/${pkg}/pkgmap" ]; then
      /usr/sbin/pkgchk -n -m "/var/sadm/pkg/${pkg}/save/pspool/${pkg}/pkgmap"
    else
      /usr/sbin/pkgchk -n "${pkg}"
    fi
  else
    echo "No such package $pkg"
  fi
done
