#!/bin/ksh
#
# clean the cache
# -a - everything
# -i - anything that's installed
# -o - anything that's not current
# -u - anything unknown
#

ZAPLIBDIR="/usr/lib/zap"
IPKGDIR="/var/sadm/pkg"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	IPKGDIR="${DESTROOT}/var/sadm/pkg"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

CACHE_DIR=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`

if [ ! -d ${CACHE_DIR} ]; then
    echo "ERROR: cache directory ${CACHE_DIR} doesn't exist"
    exit 1
fi

cd ${CACHE_DIR}

case $1 in
    -a)
	/usr/bin/rm -f *.zap
	/usr/bin/rm -f *.zap.sig
	;;

    -u)

for apkg in *.zap
do
    pkg=${apkg%%.*}
    ${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | read fpkg frepo
    if [ -z "$frepo" ]; then
	echo "Removing unknown: $apkg"
	/usr/bin/rm -f $apkg ${apkg}.sig
    fi
done
;;

    -i)
for apkg in *.zap
do
    pkg=${apkg%%.*}
    if [ -d ${IPKGDIR}/${pkg} ]; then
	echo "Removing installed: $apkg"
	/usr/bin/rm -f $apkg ${apkg}.sig
    fi
done
;;

    -o)
for apkg in *.zap
do
    pkg=${apkg%%.*}
    ${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | read fpkg frepo
    if [ -n "$frepo" ]; then
	cpkg="${fpkg}.zap"
	if [ "X${cpkg}" != "X${apkg}" ]; then
	    echo "Removing old: $apkg (current is $fpkg)"
	    /usr/bin/rm -f $apkg ${apkg}.sig
	fi
    fi
done
;;

esac
