#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# clean the cache
# -a - everything
# -i - anything that's installed
# -o - anything that's not current
# -u - anything unknown
#

ZAPLIBDIR="/usr/lib/zap"
IPKGDIR="/var/sadm/pkg"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	IPKGDIR="${DESTROOT}/var/sadm/pkg"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

CACHE_DIR=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir)

if [ ! -d "${CACHE_DIR}" ]; then
    echo "ERROR: cache directory ${CACHE_DIR} doesn't exist"
    exit 1
fi

cd "${CACHE_DIR}" || exit 1

case $1 in
    -a)
	/usr/bin/rm -f ./*.zap
	/usr/bin/rm -f ./*.zap.sig
	;;

    -u)

for apkg in *.zap
do
    pkg=${apkg%%.*}
    ${ZAPLIBDIR}/get-version ${CTXARGS} "$pkg" | read -r fpkg frepo
    if [ -z "$frepo" ]; then
	echo "Removing unknown: $apkg"
	/usr/bin/rm -f "$apkg" "${apkg}.sig"
    fi
done
;;

    -i)
for apkg in *.zap
do
    pkg=${apkg%%.*}
    if [ -d "${IPKGDIR}/${pkg}" ]; then
	echo "Removing installed: $apkg"
	/usr/bin/rm -f "$apkg" "${apkg}.sig"
    fi
done
;;

    -o)
for apkg in *.zap
do
    pkg=${apkg%%.*}
    ${ZAPLIBDIR}/get-version ${CTXARGS} "$pkg" | read -r fpkg frepo
    if [ -n "$frepo" ]; then
	cpkg="${fpkg}.zap"
	if [ "X${cpkg}" != "X${apkg}" ]; then
	    echo "Removing old: $apkg (current is $fpkg)"
	    /usr/bin/rm -f "$apkg" "${apkg}.sig"
	fi
    fi
done
;;

    *)
exit 2
;;

esac
