#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# copy an overlay repo from a source URL to a destination path
#
# note that this script is also designed to be run standalone
# so it cannot depend on the rest of the zap machinery
#

ZAPLIBDIR="/usr/lib/zap"

if [ -x "${ZAPLIBDIR}/zap-cfg" ]; then
    USER_AGENT="copy-repo"/$(${ZAPLIBDIR}/zap-cfg pkgversion)
else
    USER_AGENT="copy-repo/standalone"
fi
CURL=/usr/bin/curl
CARGS="-A ${USER_AGENT} -f -s -o"

#
# arguments are
#   repo destination
# or
#   url destination
#
# if the destination does not exist it will be created and the repo copied
# if the destination exists and contains a catalog, it will be updated
#
# you can either specify a repo by name or url
# url is more reliable, as it allows you to specify the
# version of the repo, just specifying the repo by name
# will pick whatever matches the currently installed system
#
usage() {
	echo "Usage: $0 repo destination"
	exit 2
}

case $# in
2)
	REPO=$1
	DESTDIR=$2
	;;
*)
	usage
	;;
esac

#
# check arguments
#
if [ -f "/etc/zap/repositories/${REPO}.ovl" ]; then
   REPO=$(grep '^URL=' "/etc/zap/repositories/${REPO}.ovl" | awk -F= '{print $2}')
fi
case $DESTDIR in
/*)
	;;
*)
	echo "Destination should be an absolute path"
	usage
	;;
esac

case $REPO in
http*)
	;;
*)
	echo "Repository should specify a URL"
	usage
	;;
esac

if [ -d "${DESTDIR}" ]; then
    if [ ! -f "${DESTDIR}"/catalog ]; then
	echo "Destination exists but doesn't look like a valid repository"
	usage
    fi
fi

PARENTDIR=${DESTDIR%/*}

if [ ! -d "${PARENTDIR}" ]; then
   echo "Parent directory not found"
   usage
fi

#
# make the directory if necessary
#
mkdir -p "$DESTDIR"
if [ ! -d "${DESTDIR}" ]; then
   echo "ERROR: unable to create destination directory"
   exit 1
fi

#
# grab the catalog and other metadata
#
${CURL} ${CARGS} "${DESTDIR}"/catalog "${REPO}"/catalog

if [ ! -f "${DESTDIR}/catalog" ]; then
   echo "ERROR: no catalog retrieved"
   exit 1
fi

if [ ! -s "${DESTDIR}/catalog" ]; then
   echo "ERROR: catalog is empty"
   exit 1
fi

#
# and grab all the files
#
awk -F'|' '{print $1,$2}' "${DESTDIR}"/catalog | while read -r ovl ver
do
    if [ ! -f "${DESTDIR}/${ovl}.ovl" ]; then
	echo "Getting ${ovl}.ovl"
	${CURL} ${CARGS} "${DESTDIR}/${ovl}.ovl" "${REPO}/${ovl}.ovl"
	echo "Getting ${ovl}.pkgs"
	${CURL} ${CARGS} "${DESTDIR}/${ovl}.pkgs" "${REPO}/${ovl}.pkgs"
    else
	iver="0"
	while read -r line
	do
	    case $line in
		VERSION*)
		    iver=${line#*=}
		    break
		    ;;
	    esac
	done<"${DESTDIR}/${ovl}.ovl"
	if [ "X${ver}" != "X${iver}" ]; then
	    echo "Updating ${ovl}.ovl"
	    ${CURL} ${CARGS} "${DESTDIR}/${ovl}.ovl" "${REPO}/${ovl}.ovl"
	    echo "Updating ${ovl}.pkgs"
	    ${CURL} ${CARGS} "${DESTDIR}/${ovl}.pkgs" "${REPO}/${ovl}.pkgs"
	fi
    fi
done
