#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# Create a zone template, which is an OS image that can be used to create
# sparse-root zones rather than using the global zone. The template itself
# is created just like a zone, but is a full zone, so has to be either
# whole-root or alien-root.
#
# Usage:
#
#  -T name of template
#  -t brand - whole, alien [default whole]
#  -I image file to install for alien template
#  -o overlay for partial root [can be multiple, passed to install]
#  -O add overlay [can be multiple, passed to install]
#  -p package for partial root [can be multiple, passed to install]
#  -P add package [can be multiple, passed to install]
#

ZAPLIBDIR="/usr/lib/zap"
ZROOTBASE="/export/zone-templates"
ZBRAND=whole
ZISOFILE=""
ZOVERLAY=""
ZADDOVERLAY=""
ZPACKAGE=""
ZADDPACKAGE=""

usage() {
  echo "Usage: $0 [-t whole|alien] -T template_name"
  echo "  [-I image_file] [-o overlay] [-O overlay] [-p package] [-P package]"
  exit 1
}

while getopts "T:t:I:o:O:p:P:" opt; do
case $opt in
T)
	TNAME="$OPTARG"
	;;
t)
	ZBRAND="$OPTARG"
	;;
I)
	ZISOFILE="$OPTARG"
	;;
o)
	ZOVERLAY="${ZOVERLAY} $OPTARG"
	;;
O)
	ZADDOVERLAY="${ZADDOVERLAY} $OPTARG"
	;;
p)
	ZPACKAGE="${ZPACKAGE} $OPTARG"
	;;
P)
	ZADDPACKAGE="${ZADDPACKAGE} $OPTARG"
	;;
*)
	usage
	;;
esac
done

THISZONE=$(/sbin/zonename)
if [ "X$THISZONE" != "Xglobal" ]; then
    echo "ERROR: zone management is only possible in the global zone"
    exit 1
fi

if [[ -z $TNAME ]]; then
   echo "ERROR: template name must be specified"
   usage
fi

#
# the naming convention for the template adds a TRIBtemplate- prefix
# check for conflicts
#
TBRANDFILE="/etc/zones/TRIBtemplate-${TNAME}.xml"
if [ -f "$TBRANDFILE" ]; then
    echo "ERROR: Template $TNAME is already in use"
    exit 1
fi

#
# check valid brand
#
# note that the brand determines how the template is created, all zones
# created using this template will be sparse
#
case $ZBRAND in
    whole)
	if [[ -n $ZISOFILE ]]; then
	    echo "ERROR: an image is valid only for alien templates"
	    exit 1
	fi
	;;
    alien)
	if [[ -z $ZISOFILE ]]; then
	    echo "ERROR: an image is required for alien templates"
	    exit 1
	fi
	if [[ -n $ZOVERLAY || -n $ZADDOVERLAY ]]; then
	    echo "ERROR: cannot specify overlays for alien templates"
	    exit 1
	fi
	if [[ -n $ZPACKAGE || -n $ZADDPACKAGE ]]; then
	   echo "ERROR: cannot specify packages for alien templates"
	   usage
	fi
	if [[ $ZISOFILE != /* ]]; then
	    #
	    # check validity of the name
	    #
	    DLFILE=$(${ZAPLIBDIR}/retrieve-image -n "$ZISOFILE")
	    if [[ $DLFILE = /* ]]; then
		if [ -f "$DLFILE" ]; then
		    echo "Using cached image $DLFILE for $ZISOFILE"
		    ZISOFILE="$DLFILE"
		else
		    echo "Downloading $ZISOFILE"
		    DLFILE=$(${ZAPLIBDIR}/retrieve-image "$ZISOFILE")
		    if [ -f "$DLFILE" ]; then
			echo "Using downloaded image $DLFILE for $ZISOFILE"
			ZISOFILE="$DLFILE"
		    fi
		fi
	    fi
	fi
	if [[ $ZISOFILE != /* ]]; then
	    echo "ERROR: image name must be absolute or specify a valid download"
	    usage
	fi
	if [ ! -f "$ZISOFILE" ]; then
	    echo "ERROR: specified image not found"
	    usage
	fi
	;;
    *)
	echo "ERROR: templates cannot be created with the $ZBRAND brand"
	exit 1
	;;
esac

#
# check any overlays are valid
# -o - error if this overlay isn't installed
# -o/-O - error if this is not a valid overlay
#
for OVL in $ZOVERLAY
do
	if [ ! -f "/var/sadm/overlays/${OVL}.ovl" ]; then
	    echo "ERROR: unrecognized overlay ${OVL}"
	    exit 1
	fi
	if [ ! -f "/var/sadm/overlays/installed/${OVL}" ]; then
	    echo "ERROR: overlay ${OVL} is not installed in the global zone"
	    exit 1
	fi
done
for OVL in $ZADDOVERLAY
do
	if [ ! -f "/var/sadm/overlays/${OVL}.ovl" ]; then
	    echo "ERROR: unrecognized overlay ${OVL}"
	    exit 1
	fi
done
#
# check any packages are valid
# -p - error if this package isn't installed
#
for APKG in $ZPACKAGE
do
    NPKG=$(/usr/lib/zap/resolve-alias "$APKG")
    if [ ! -f "/var/sadm/pkg/${NPKG}/pkginfo" ]; then
	echo "ERROR: unrecognized package ${APKG}"
	exit 1
    fi
done

#
# sanity check that the appropriate zone infrastructure is installed
#
if [ ! -f /var/sadm/pkg/TRIBblix-zones/pkginfo ]; then
    echo "ERROR: the TRIBblix-zones package is not installed"
    exit 1
fi
if [ ! -f /etc/zones/TRIBsparse.xml ]; then
    echo "ERROR: the sparse brand cannot be found"
    echo "  (something appears to be corrupt)"
    exit 1
fi
if [ ! -f /usr/lib/brand/${ZBRAND}-root/pkgcreatezone ]; then
    echo "ERROR: the ${ZBRAND} brand cannot be found"
    echo "  (something appears to be corrupt)"
    exit 1
fi

create_install_opts() {
for OVL in $ZOVERLAY
do
    printf " -o $OVL"
done
for OVL in $ZADDOVERLAY
do
    printf " -O $OVL"
done
for APKG in $ZPACKAGE
do
	printf " -p $APKG"
done
for APKG in $ZADDPACKAGE
do
	printf " -P $APKG"
done
if [[ -n $ZISOFILE ]]; then
    printf " -i $ZISOFILE"
fi
}

#
# create any missing zfs datasets
#
if [ ! -d "${ZROOTBASE}" ]; then
   ZPARENT=${ZROOTBASE%/*}
   ZDPARENT=$(/usr/sbin/zfs list -H "${ZPARENT}" | /usr/bin/awk '{print $1}')
   ZREALNAME=$(echo $ZROOTBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
   /usr/sbin/zfs create "${ZREALNAME}"
fi
if [ ! -d "${ZROOTBASE}/${TNAME}" ]; then
   ZPARENT=${ZROOTBASE%/*}
   ZDPARENT=$(/usr/sbin/zfs list -H "${ZPARENT}" | /usr/bin/awk '{print $1}')
   ZREALNAME=$(echo $ZROOTBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
   /usr/sbin/zfs create "${ZREALNAME}/${TNAME}"
fi

#
# call the relevant pkgcreatezone by hand
# we want to specify just the zone root, but have to supply a zone name
# as well
#
/usr/lib/brand/${ZBRAND}-root/pkgcreatezone -T -R "${ZROOTBASE}/${TNAME}" -z "template-${TNAME}" $(create_install_opts)

#
# Now create a zone xml file that matches the template locations
# we just populated
#
/usr/bin/sed -e s:special=\"/usr:special=\"${ZROOTBASE}/${TNAME}/usr: -e s:special=\"/sbin:special=\"${ZROOTBASE}/${TNAME}/sbin: -e s:special=\"/platform:special=\"${ZROOTBASE}/${TNAME}/platform: -e s:special=\"/zonelib/lib:special=\"${ZROOTBASE}/${TNAME}/lib: /etc/zones/TRIBsparse.xml > "${TBRANDFILE}"
