#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# deletes those packages passed on the command line
#
ZAPLIBDIR="/usr/lib/zap"
UTEXT=""

#
# called with -u if part of update
#
case $1 in
-u)
    UTEXT="old version of "
    shift
    ;;
esac

case $1 in
-R)
    DESTROOT="$2"
    BFLAGS="-R ${DESTROOT}"
    shift
    shift
    if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	echo "ERROR: alternate root $DESTROOT is invalid"
	exit 1
    fi
    ;;
esac

for pkg in $(${ZAPLIBDIR}/resolve-alias "$@")
do
	if [ -f "${DESTROOT}/var/sadm/pkg/${pkg}/pkginfo" ]; then
                echo "Removing ${UTEXT}$pkg"
                /usr/sbin/pkgrm -n -a ${ZAPLIBDIR}/pkg.force ${BFLAGS} "$pkg"
        fi
done
