#!/bin/sh
#
# deletes those packages passed on the command line
#
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-R)
    BFLAGS="-R $2"
    shift
    shift
    ;;
esac

for inpkg in $*
do
	pkg=`${ZAPLIBDIR}/resolve-alias $inpkg`
	if /usr/bin/pkginfo ${BFLAGS} -q ${pkg}
	then
                echo "Removing $pkg package"
                /usr/sbin/pkgrm -n -a ${ZAPLIBDIR}/pkg.force ${BFLAGS} $pkg
        fi
done
