#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

ODIR="/var/sadm/overlays"
DESTROOT=""

case $1 in
-R)
	DESTROOT="$2"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/${ODIR}" ]; then
	    echo "ERROR: alternate overlay directory $DESTROOT/$ODIR doesn't exist"
	    exit 1
	fi
	;;
esac

#
if [ ! -d "${DESTROOT}/${ODIR}" ]; then
    exit 0
fi
cd "${DESTROOT}/${ODIR}" || exit 1
for OVL in "$@"
do
    FOVL=${OVL}.ovl
    if [ -f "${DESTROOT}/${ODIR}/${FOVL}" ]; then
	echo "OVERLAY: $OVL"
	cat "${DESTROOT}/${ODIR}/${FOVL}"
	if [ -f "${DESTROOT}/${ODIR}/installed/$OVL" ]; then
	    STATUS="Installed"
	else
	    STATUS="Not installed"
	fi
	echo "STATUS=$STATUS"
    else
	echo "ERROR: no such overlay $OVL"
    fi
    echo ""
done
