#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# generate a version 5 UUID
#
# xxxxxxxx-xxxx-5xxx-Yxxx-xxxxxxxxxxxx
# and Y is one of 8,9,A,B
#

#
# first generate a random hash
#
# Don't use /dev/random as it will block if entropy is low
# for example, under Xen
#
HASH=$(/usr/bin/head -c 32 /dev/urandom | /usr/bin/digest -a sha1)

#
# cut it into pieces
# emit in the correct format
#
echo "${HASH:0:8}-${HASH:8:4}-5${HASH:13:3}-9${HASH:17:3}-${HASH:20:12}"
