#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-R|-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

#
# this script is also the back end for a pkgdep emulator
# by default, list all dependencies, with -c just print the
# uninstalled dependencies
#
DOALL="y"
case $1 in
    -c)
	DOALL=""
	shift
	;;
esac

#
# assume aliases have been resolved by the caller
#
case $# in
1)
	PKG=$1
	;;
*)
	exit 2
	;;
esac

#
# given a package, return the dependencies present in the catalog
#
repo=$(${ZAPLIBDIR}/get-version ${CTXARGS} "${PKG}")
repo=${repo#* }
if [ -f "${CFGDIR}/repositories/${repo}.catalog" ]; then
    for npkg in $(/usr/bin/awk -F'|' '{if ($1 == npkg) print $3}' npkg="${PKG}" "${CFGDIR}/repositories/${repo}.catalog")
    do
	if [ -n "${DOALL}" ]; then
	    echo "${npkg}"
	else
	    if [ ! -f "${DESTROOT}/var/sadm/pkg/${npkg}/pkginfo" ]; then
		echo "${npkg}"
	    fi
	fi
    done
else
    exit 1
fi
