#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

#
# assume aliases have been resolved by the caller
#
case $# in
1)
	PKG=$1
	;;
*)
	exit 2
	;;
esac

#
# given a package, return the uninstalled dependencies present in the catalog
#
repo=$(${ZAPLIBDIR}/get-version ${CTXARGS} "${PKG}")
repo=${repo#* }
if [ -f "${CFGDIR}/repositories/${repo}.catalog" ]; then
    for npkg in $(/usr/bin/awk -F'|' '{if ($1 == npkg) print $3}' npkg="${PKG}" "${CFGDIR}/repositories/${repo}.catalog")
    do
	if [ ! -f "${DESTROOT}/var/sadm/pkg/${npkg}/pkginfo" ]; then
	    echo "${npkg}"
	fi
    done
fi
