#!/bin/ksh
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

#
# given an unqualified package, return a qualified package and the name
# of the repo it's contained in
#
repolist=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos`
for PKG in $*
do
    PFOUND=""
    for repo in $repolist
    do
	if [ -f ${CFGDIR}/repositories/${repo}.catalog ]; then
	    FPKG=`/usr/bin/nawk -F'|' '{if ($1 == npkg) print $1"."$2}' npkg=${PKG} ${CFGDIR}/repositories/${repo}.catalog`
	    if [ -n "$FPKG" ]; then
		echo "${FPKG} ${repo}"
		PFOUND="y"
		break
	    fi
	fi
    done
    if [ -z "$PFOUND" ]; then
	echo $PKG
    fi
done
