#!/bin/ksh
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

case $# in
1)
	OVL="$1"
	;;
*)
	exit 1
	;;
esac

#
# given an overlay, return its name, version, and repo
# as given in the catalog
#
for repo in `${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-overlay-repos`
do
    if [ -f ${CFGDIR}/repositories/${repo}.overlays ]; then
	FOVL=`/usr/bin/nawk -F'|' '{if ($1 == novl) print $1,$2}' novl=${OVL} ${CFGDIR}/repositories/${repo}.overlays`
	if [ -n "$FOVL" ]; then
	    echo "${FOVL} ${repo}"
	    exit 0
	fi
    fi
done
