#!/bin/sh
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"
ECHO="true"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

#
# assume aliases have been resolved by the caller
#
case $# in
1)
	PKG=$1
	;;
*)
	exit 1
	;;
esac

#
# given a package, return the uninstalled dependencies present in the catalog
#
repo=`${ZAPLIBDIR}/get-version ${CTXARGS} ${PKG}`
repo=${repo#* }
if [ -f ${CFGDIR}/repositories/${repo}.catalog ]; then
    FPKG=`/usr/bin/awk -F'|' '{if ($1 == npkg) print $3}' npkg=${PKG} ${CFGDIR}/repositories/${repo}.catalog`
    if [ -n "$FPKG" ]; then
	for npkg in $FPKG
	do
	    if [ ! -f ${DESTROOT}/var/sadm/pkg/${npkg}/pkginfo ]; then
		echo "${npkg}"
	    fi
	done
	exit 0
    fi
fi
