#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

case $# in
1)
	PKG="$1"
	;;
*)
	exit 2
	;;
esac

#
# given a package, return its name, version, size, hash, and repo
# as given in the catalog
#
for repo in $(${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos)
do
    if [ -f "${CFGDIR}/repositories/${repo}.catalog" ]; then
	FPKG=$(/usr/bin/awk -F'|' '{if ($1 == npkg) print $1,$2,$4,$5}' npkg="${PKG}" "${CFGDIR}/repositories/${repo}.catalog")
	if [ -n "$FPKG" ]; then
	    echo "${FPKG} ${repo}"
	    exit 0
	fi
    fi
done
