#!/bin/sh
#
# installs a package if not already installed
#
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-R)
    BFLAGS="-R $2"
    shift
    shift
    ;;
esac

case $# in
2)
    DIR=$1
    PKG=$2
    ;;
*)
    echo "Usage: instpkg [-R alt-root] source package"
    exit 1
    ;;
esac

/usr/bin/pkginfo ${BFLAGS} -q ${PKG}
FOUNDPKG=$?
#
# install if not found
#
if [ $FOUNDPKG -eq 0 ]; then
    echo "Package $PKG already installed"
else
    if [ ! -d ${DIR} -a ! -f ${DIR} ]; then
	echo "Source ${DIR} doesn't exist"
	exit 1
    fi
    echo "Installing $PKG"
    /usr/sbin/pkgadd -n -a ${ZAPLIBDIR}/pkg.force ${BFLAGS} -d ${DIR} ${PKG}
fi
