#!/bin/ksh

ONAME=""
ZAPLIBDIR="/usr/lib/zap"
ODIR="/var/sadm/overlays"
INSTODIR="${ODIR}"
CFGODIR="${ODIR}"
PKGARGS=""
DESTROOT=""
SRCARGS=""

case $1 in
-C)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGODIR="${DESTROOT}/${ODIR}"
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-s)
	SRCDIR="$2"
	SRCARGS="-s ${SRCDIR}"
	shift
	shift
	if [ ! -d "$SRCDIR" ]; then
	    echo "WARN: package source $SRCDIR doesn't exist"
	    SRCARGS=""
	fi
	;;
esac

case $# in
1)
	ONAME="$1"
	;;
*)
	echo "Usage: $0 [-C|-R alt-root] [-s pkg_source] overlay"
	exit 1
	;;
esac

#
# if installed, just exit
# if someone has messed with packages behind our back, they suffer
#
if [ -f "${INSTODIR}/installed/${ONAME}" ]; then
    exit 0
fi

OVL="${CFGODIR}/${ONAME}.ovl"
if [ ! -f "${OVL}" ]; then
    echo "ERROR: invalid overlay ${ONAME}"
    exit 1
fi
PLIST="${CFGODIR}/${ONAME}.pkgs"
if [ ! -f "${PLIST}" ]; then
    echo "ERROR: package list for overlay ${ONAME} missing"
    exit 1
fi

#
# install dependent overlays, if any
#
for nnovl in $(/usr/bin/grep '^REQUIRES=' "${OVL}")
do
    novl=${nnovl/REQUIRES=/}
    if [ ! -f "${INSTODIR}/installed/${novl}" ]; then
	${ZAPLIBDIR}/install-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} "${novl}"
    fi
done

${ZAPLIBDIR}/install-pkg ${CTXARGS} ${PKGARGS} ${SRCARGS} $(<${PLIST})
OVSUCCESS=$?

#
# book keeping
#
if [ $OVSUCCESS -eq 0 ]; then
    echo "Overlay ${ONAME} installation succeeded"
    mkdir -p "${INSTODIR}/installed"
    touch "${INSTODIR}/installed/${ONAME}"
else
    echo "Errors in installation of overlay ${ONAME}"
fi
