#!/bin/ksh
#
# installs a package from a zap file if not already installed
#
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-R)
    BFLAGS="-R $2"
    shift
    shift
    ;;
esac

case $# in
2)
    DIR=$1
    PKG=$2
    ;;
*)
    echo "Usage: instzap [-R alt-root] source package"
    exit 1
    ;;
esac

/usr/bin/pkginfo ${BFLAGS} -q ${PKG}
FOUNDPKG=$?
#
# install if not found
#
if [ $FOUNDPKG -eq 0 ]; then
    echo "Package $PKG already installed"
else
    if [ ! -f ${DIR} ]; then
	echo "Zap source file ${DIR} doesn't exist"
	exit 1
    fi
    echo "Installing $PKG"
    ZTMP=/tmp/zap.tmp.`date '+%F-%T'`.$$
    /usr/bin/rm -fr ${ZTMP}
    /usr/bin/mkdir ${ZTMP}
    cd ${ZTMP}
    #
    # prefer unzip, as it is quieter and quicker, but fall back on
    # alternatives if necessary
    #
    if [ -x /usr/bin/unzip ]; then
	/usr/bin/unzip -q ${DIR}
    elif [ -x /usr/bin/7z ]; then
	/usr/bin/7z x ${DIR}
    else
	jar xf $DIR
    fi
    cd /
    /usr/sbin/pkgadd -n -a ${ZAPLIBDIR}/pkg.force ${BFLAGS} -d ${ZTMP} ${PKG}
    /usr/bin/rm -fr $ZTMP
fi
