#!/bin/ksh

ZAPLIBDIR="/usr/lib/zap"
PKGARGS=""
DESTROOT=""
NINSTALLED=0
NFAILED=0
DOPKGS=""

case $1 in
-C)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

SRCLIST=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`

#
# if we have access to a global cache, prepend that
#
if [ -d /var/zap/global-cache ]; then
    SRCLIST="/var/zap/global-cache $SRCLIST"
fi

#
# prepend the given source to the list, so it gets searched first
#
case $1 in
-s)
	SRCEXTRA="$2"
	shift
	shift
	if [ ! -d "$SRCEXTRA" ]; then
	    echo "ERROR: package source $SRCEXTRA doesn't exist"
	    exit 1
	fi
	SRCLIST="$SRCEXTRA $SRCLIST"
	;;
esac

case $# in
0)
	echo "Usage: $0 [-R alt-root] [ -s source] package [package...]"
	exit 1
	;;
esac

#
# FIXME:
#  fail if there are missing packages after first pass
#

#
# first look for and download any packages we need
#
for inpkg in $*
do
  pkg=`${ZAPLIBDIR}/resolve-alias ${CTXARGS} $inpkg`
  /usr/bin/pkginfo ${PKGARGS} -q ${pkg}
  FOUNDPKG=$?
  if [ $FOUNDPKG -eq 0 ]; then
    echo "Package $pkg already installed"
  else
    DOPKGS="${DOPKGS} $pkg"
    ISINST="false"
    fpkg=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | /usr/bin/awk '{print $1}'`
    for SRCDIR in $SRCLIST
    do
	if [ -f ${SRCDIR}/${fpkg}.zap ]; then
	    ISINST="true"
	    break
	fi
    done
    # download if we don't have it yet
    if [ "$ISINST" = "false" ]; then
	${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} ${pkg}
    fi
  fi
done

#
# we have resolved all names and only have uninstalled packages,
# so no need to check again
#
for pkg in $DOPKGS
do
  ISINST="false"
  fpkg=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | /usr/bin/awk '{print $1}'`
  for SRCDIR in $SRCLIST
  do
    if [ -f ${SRCDIR}/${fpkg}.zap ]; then
      ${ZAPLIBDIR}/instzap ${PKGARGS} ${SRCDIR}/${fpkg}.zap ${pkg}
      ISINST="true"
      break
    fi
  done
  if [ "$ISINST" = "false" ]; then
    echo "No source for package ${pkg}"
    NFAILED=$(($NFAILED+1))
  else
    NINSTALLED=$(($NINSTALLED+1))
  fi
done

if [ $NFAILED -eq 0 ]; then
    echo Installed $NINSTALLED packages
else
    echo Installed $NINSTALLED packages, $NFAILED failed
fi

exit $NFAILED
