#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

ODIR="/var/sadm/overlays"
DESTROOT=""

case $1 in
-R)
	DESTROOT="$2"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/${ODIR}" ]; then
	    echo "ERROR: alternate overlay directory $DESTROOT/$ODIR doesn't exist"
	    exit 1
	fi
	;;
esac

INST=""
UNINST=""
VERBOSE=""

while getopts "iuv" opt; do
case $opt in
i)
  INST="y"
  ;;
u)
  UNINST="y"
  ;;
v)
  VERBOSE="y"
  ;;
esac
done
shift $((OPTIND - 1))

#
# it makes no sense to have both -i and -u
#
if [[ -n "$INST" && -n "$UNINST" ]]; then
    echo "ERROR: both -i and -u supplied"
    exit 1
fi

#
# for verbose we want the overlay descriptions
# grab them in one pass here
#
typeset -A omap
if [[ -n "$VERBOSE" ]]; then
    grep '^NAME=' "${DESTROOT}"/${ODIR}/*.ovl | while read -r line
    do
	namestr=${line##*:}
	namestr=${namestr##*=}
	fstr=${line%%:*}
	omap[$fstr]="$namestr"
    done
fi

print_verbose() {
    if [[ -n "$VERBOSE" ]]; then
	echo "${1} [${omap[${DESTROOT}/${ODIR}/${OVL}.ovl]}] ${2}"
    else
	echo "${1} ${2}"
    fi
}

#
# default: list all overlays
#
if [ ! -d "${DESTROOT}/${ODIR}" ]; then
    exit 0
fi
cd "${DESTROOT}/${ODIR}" || exit 1

#
# loop through all overlays
#
if [[ -n "$INST" ]]; then
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ -f "${DESTROOT}/${ODIR}/installed/$OVL" ]; then
	    print_verbose "$OVL"
	fi
    done
elif [[ -n "$UNINST" ]]; then
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ ! -f "${DESTROOT}/${ODIR}/installed/$OVL" ]; then
	    print_verbose "$OVL"
	fi
    done
else
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ -f "${DESTROOT}/${ODIR}/installed/$OVL" ]; then
	    STATUS="Installed"
	else
	    STATUS="Not installed"
	fi
	print_verbose "$OVL" "($STATUS)"
    done
fi
