#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# list zone templates
#

#
# this is just the naming convention
#
for TFILE in /etc/zones/TRIBtemplate-*.xml
do
  if [ -f "$TFILE" ]; then
    TNAME=${TFILE#*-}
    TNAME=${TNAME%.xml}
    UDIR=$(/usr/bin/grep 'directory=\"/usr\"' "${TFILE}" | /usr/bin/awk '{print $2}' | /usr/bin/awk -F= '{print $2}' | /usr/bin/sed 's:"::g')
    UROOT=${UDIR%/usr}
    ZLIST=$(/usr/bin/grep 'special=\"'${UDIR}'\"' /etc/zones/*.xml | /usr/bin/grep -v '^'$TFILE| /usr/bin/awk -F: '{print $1}')
    echo "Template: $TNAME"
    echo "  Root: $UROOT"
    echo "  Zones: "
    for ZFILE in $ZLIST
    do
	ZNAME=${ZFILE#/etc/zones/}
	ZNAME=${ZNAME%.xml}
	echo "    $ZNAME"
    done
    echo ""
  fi
done
