#!/bin/sh

ODIR="/var/sadm/overlays"
DESTROOT=""

case $1 in
-R)
	DESTROOT="$2"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

INST=""
UNINST=""
VERBOSE=""

while getopts "iuv" opt; do
case $opt in
i)
  INST="y"
  ;;
u)
  UNINST="y"
  ;;
v)
  VERBOSE="y"
  ;;
esac
done
shift $((OPTIND - 1))

#
# it makes no sense to have both -i and -u
#
if [[ -n "$INST" && -n "$UNINST" ]]; then
    echo "ERROR: both -i and -u supplied"
    exit 1
fi

print_verbose() {
    if [[ -n "$VERBOSE" ]]; then
	DESC=`awk -F= '{if ($1 == "NAME") print $2}' ${DESTROOT}/${ODIR}/${OVL}.ovl`
	echo "${1} [${DESC}] ${2}"
    else
	echo "${1} ${2}"
    fi
}

#
# default: list all overlays
#
if [ ! -d ${DESTROOT}/${ODIR} ]; then
    exit 0
fi
cd ${DESTROOT}/${ODIR}

#
# loop through all overlays
#
if [[ -n "$INST" ]]; then
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ -f ${DESTROOT}/${ODIR}/installed/$OVL ]; then
	    print_verbose "$OVL"
	fi
    done
elif [[ -n "$UNINST" ]]; then
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ ! -f ${DESTROOT}/${ODIR}/installed/$OVL ]; then
	    print_verbose "$OVL"
	fi
    done
else
    for FOVL in *.ovl
    do
	OVL=${FOVL%.ovl}
	if [ -f ${DESTROOT}/${ODIR}/installed/$OVL ]; then
	    STATUS="Installed"
	else
	    STATUS="Not installed"
	fi
	print_verbose "$OVL" "($STATUS)"
    done
fi
