#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# given a package, return its dependencies
# expects either a zap file, or an installed package name
#

case $# in
1)
	pkgname="$1"
	;;
*)
	echo "Usage: $0 pkg"
	exit 1
	;;
esac

case $pkgname in
*.zap)
	if [ -f ${pkgname} ]; then
	   thispkg=${pkgname##*/}
	   zipgrep '^P' ${pkgname} ${thispkg%%.*}/install/depend 2>/dev/null | /usr/bin/awk '{print $2}'
	   exit 0
	else
	   exit 1
	fi
	;;
*)
	if [ -f /var/sadm/pkg/${pkgname}/install/depend ]; then
	   /usr/bin/grep '^P' /var/sadm/pkg/${pkgname}/install/depend | /usr/bin/awk '{print $2}'
	   exit 0
	fi
	;;
esac
