#!/bin/ksh
#
# given a package, returns the version of it
# expects either a pkg or zap file, or an installed package name
#

ALTROOT=""
case $1 in
-R)
    ALTROOT="$2"
    shift
    shift
    ;;
esac

case $# in
1)
	pkgname="$1"
	;;
*)
	echo "Usage: $0 pkg"
	exit 1
	;;
esac

case $pkgname in
*.zap)
	if [ -f ${pkgname} ]; then
	   thispkg=${pkgname##*/}
	   /usr/bin/zipgrep VERSION= ${pkgname} ${thispkg%%.*}/pkginfo | /usr/bin/awk -F= '{gsub("\"","",$2);print $2}'
	   exit 0
	else
	   echo "Error: unable to find package file $pkgname"
	   exit 1
	fi
	;;
*.pkg)
	if [ -f ${pkgname} ]; then
	   /usr/bin/pkginfo -l -d ${pkgname} | /usr/bin/grep VERSION: | /usr/bin/awk '{gsub("\"","",$NF);print $NF}'
	   exit 0
	else
	   echo "Error: unable to find package file $pkgname"
	   exit 1
	fi
	;;
*)
	if [ -f ${ALTROOT}/var/sadm/pkg/${pkgname}/pkginfo ]; then
	    IVERSION=""
	    while read line
	    do
		case $line in
		    VERSION*)
			IVERSION=${line#*=}
			break
			;;
		esac
	    done<${ALTROOT}/var/sadm/pkg/${pkgname}/pkginfo
	    echo $IVERSION
	    exit 0
	else
	   echo "Error: unable to find package $pkgname"
	   exit 1
	fi
	;;
esac
