#!/bin/sh
#
# generate a list of system files that should be preserved
# these are files of type 'e' (editable) in SVR4 packaging
# that have been modified
#

CFILE="/var/sadm/install/contents"
AWK="/usr/bin/nawk"
DIFF="/usr/bin/diff"
VERBOSE="n"

case $1 in
-v)
    VERBOSE="y"
    ;;
esac

$AWK '{if ($2 == "e") print $1,$NF}' $CFILE | while read file pkg
do
  if [ -f $file ]; then
    $DIFF $file /var/sadm/pkg/${pkg}/save/pspool/${pkg}/reloc$file >/dev/null
    if [ $? -ne 0 ]; then
      echo "$file $pkg"
      if [ "X${VERBOSE}" = "Xy" ]; then
	echo "====================================================="
	echo "   /var/sadm/pkg/${pkg}/save/pspool/${pkg}/reloc$file"
	echo "====================================================="
	$DIFF $file /var/sadm/pkg/${pkg}/save/pspool/${pkg}/reloc$file
	echo "====================================================="
      fi
    fi
  fi
done
