#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# refreshes the file lists for all repos
#

ZAPLIBDIR="/usr/lib/zap"
CFGDIR="/etc/zap"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	;;
esac

USER_AGENT="zap"/$(${ZAPLIBDIR}/zap-cfg pkgversion)
WCLIENT=/usr/bin/curl
WARGS="-A ${USER_AGENT} -f -s -o"
if [ ! -x $WCLIENT ]; then
    WCLIENT=/usr/bin/wget
    WARGS="-U ${USER_AGENT} -q -O"
fi
if [ ! -x $WCLIENT ]; then
    WCLIENT=/usr/bin/wget2
    WARGS="-U ${USER_AGENT} -q -O"
fi

refresh_file_repo() {
    frepo="$1"
    REPO=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} repo-url $frepo)
    ${WCLIENT} ${WARGS} ${CFGDIR}/repositories/${frepo}.filelist.bz2.tmp ${REPO}/filelist.bz2
    if [ -s ${CFGDIR}/repositories/${frepo}.filelist.bz2.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.filelist.bz2 ${CFGDIR}/repositories/${frepo}.filelist.bz2.bak
	mv ${CFGDIR}/repositories/${frepo}.filelist.bz2.tmp ${CFGDIR}/repositories/${frepo}.filelist.bz2
    fi
}

for repo in $(/usr/bin/awk '{print $2}' ${CFGDIR}/repo.list)
do
    refresh_file_repo $repo
done
