#!/bin/ksh
#
# refreshes the specified repo(s), or all
#

ZAPLIBDIR="/usr/lib/zap"
CFGDIR="/etc/zap"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	;;
esac

refresh_repo() {
    frepo="$1"
    REPO=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} repo-url $frepo`
    /usr/bin/curl -f -s -o ${CFGDIR}/repositories/${frepo}.catalog.tmp ${REPO}/catalog
    if [ -s ${CFGDIR}/repositories/${frepo}.catalog.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.catalog ${CFGDIR}/repositories/${frepo}.catalog.bak
	mv ${CFGDIR}/repositories/${frepo}.catalog.tmp ${CFGDIR}/repositories/${frepo}.catalog
    fi
    /usr/bin/curl -f -s -o ${CFGDIR}/repositories/${frepo}.aliases.tmp ${REPO}/aliases
    if [ -s ${CFGDIR}/repositories/${frepo}.aliases.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.aliases ${CFGDIR}/repositories/${frepo}.aliases.bak
	mv ${CFGDIR}/repositories/${frepo}.aliases.tmp ${CFGDIR}/repositories/${frepo}.aliases
    fi
}

case $# in
0)
	for repo in `/usr/bin/sort -k1 -n ${CFGDIR}/repo.list | /usr/bin/awk '{print $2}`
	do
	    refresh_repo $repo
	done
	;;
*)
	for repo in $*
	do
	    refresh_repo $repo
	done
	;;
esac
