#!/bin/ksh
#
# refreshes the catalogs for all repos
#

ZAPLIBDIR="/usr/lib/zap"
CFGDIR="/etc/zap"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	;;
esac

USER_AGENT="zap"/$(${ZAPLIBDIR}/pkgversion TRIBzap)
WCLIENT=/usr/bin/curl
WARGS="-A ${USER_AGENT} -f -s --compressed -o"
if [ ! -x $WCLIENT ]; then
    WCLIENT=/usr/bin/wget
    WARGS="-U ${USER_AGENT} -q --compression=gzip -O"
fi

refresh_repo() {
    frepo="$1"
    REPO=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} repo-url $frepo)
    ${WCLIENT} ${WARGS} ${CFGDIR}/repositories/${frepo}.catalog.tmp ${REPO}/catalog
    if [ -s ${CFGDIR}/repositories/${frepo}.catalog.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.catalog ${CFGDIR}/repositories/${frepo}.catalog.bak
	mv ${CFGDIR}/repositories/${frepo}.catalog.tmp ${CFGDIR}/repositories/${frepo}.catalog
    fi
    ${WCLIENT} ${WARGS} ${CFGDIR}/repositories/${frepo}.aliases.tmp ${REPO}/aliases
    if [ -s ${CFGDIR}/repositories/${frepo}.aliases.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.aliases ${CFGDIR}/repositories/${frepo}.aliases.bak
	mv ${CFGDIR}/repositories/${frepo}.aliases.tmp ${CFGDIR}/repositories/${frepo}.aliases
    fi
}

for repo in $(/usr/bin/awk '{print $2}' ${CFGDIR}/repo.list)
do
    refresh_repo $repo
done
