#!/bin/ksh
#
# refreshes the specified overlay repo(s), and their overlays, or all
#

ZAPLIBDIR="/usr/lib/zap"
CFGDIR="/etc/zap"
ODIR="/var/sadm/overlays"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	ODIR="${ALTROOT}/${ODIR}"
	;;
esac

USER_AGENT="zap"/$(${ZAPLIBDIR}/pkgversion TRIBzap)
WCLIENT=/usr/bin/curl
WARGS="-A ${USER_AGENT} -f -s -o"
if [ ! -x $WCLIENT ]; then
    WCLIENT=/usr/bin/wget
    WARGS="-U ${USER_AGENT} -q -O"
fi

refresh_overlay_repo() {
    frepo="$1"
    REPO=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} overlay-url $frepo)
    ${WCLIENT} ${WARGS} ${CFGDIR}/repositories/${frepo}.overlays.tmp ${REPO}/catalog
    if [ -s ${CFGDIR}/repositories/${frepo}.overlays.tmp ]; then
	mv ${CFGDIR}/repositories/${frepo}.overlays ${CFGDIR}/repositories/${frepo}.overlays.bak
	mv ${CFGDIR}/repositories/${frepo}.overlays.tmp ${CFGDIR}/repositories/${frepo}.overlays
	/usr/bin/awk -F'|' '{print $1}' ${CFGDIR}/repositories/${frepo}.overlays | while read novl
	do
	    ${ZAPLIBDIR}/get-overlay-meta ${CTXARGS} $novl | read tovl nver trepo
	    #
	    # check that this repo is the authoritative source for this overlay
	    #
	    if [ "X$frepo" = "X$trepo" ]; then
		#
		# if the overlay file does not exist then this must be a new
		# overlay, set version 0 to force a download and don't try to
		# grep it otherwise we get a confusing error
		#
		iver="0"
		if [ -f ${ODIR}/${novl}.ovl ]; then
		    while read line
		    do
			case $line in
			    VERSION*)
				iver=${line#*=}
				break
				;;
			esac
		    done<${ODIR}/${novl}.ovl
		fi
		if [ "X${nver}" != "X${iver}" ]; then
		    ${WCLIENT} ${WARGS} ${ODIR}/${novl}.ovl.tmp ${REPO}/${novl}.ovl
		    ${WCLIENT} ${WARGS} ${ODIR}/${novl}.pkgs.tmp ${REPO}/${novl}.pkgs
		    if [ -s ${ODIR}/${novl}.ovl.tmp -a -s ${ODIR}/${novl}.pkgs.tmp ]; then
			if [ -f ${ODIR}/${novl}.ovl ]; then
			    mv ${ODIR}/${novl}.ovl ${ODIR}/${novl}.ovl.bak
			fi
			mv ${ODIR}/${novl}.ovl.tmp ${ODIR}/${novl}.ovl
			if [ -f ${ODIR}/${novl}.pkgs ]; then
			    mv ${ODIR}/${novl}.pkgs ${ODIR}/${novl}.pkgs.bak
			fi
			mv ${ODIR}/${novl}.pkgs.tmp ${ODIR}/${novl}.pkgs
		    fi
		fi
	    fi
	done
    fi
}

for repo in $(${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-overlay-repos)
do
    refresh_overlay_repo $repo
done

#
# refresh the catalog as well
#
${ZAPLIBDIR}/refresh-catalog ${CTXARGS}
