#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# remove the cdrom device from a bhyve zone, and optionally
# reboot it
#

usage() {
    echo "Usage: $0 -z zone_name [-r]"
    exit 2
}

ZONEADM="/usr/sbin/zoneadm"
ZONECFG="/usr/sbin/zonecfg"
ZNAME=""
REBOOT=""

while getopts "rz:" opt; do
case $opt in
r)
	REBOOT="y"
	;;
z)
	ZNAME="$OPTARG"
	;;
*)
	usage
	;;
esac
done

THISZONE=$(/sbin/zonename)
if [ "X$THISZONE" != "Xglobal" ]; then
    echo "ERROR: zone management is only possible in the global zone"
    exit 1
fi

if [[ -z $ZNAME ]]; then
   echo "ERROR: zone name must be specified"
   usage
fi

#
# check that the zone already exists
#
/usr/sbin/zoneadm -z "$ZNAME" list > /dev/null 2>&1
ZEXISTS=$?
if [ $ZEXISTS -ne 0 ]; then
    echo "ERROR: zone $ZNAME does not exist"
    exit 1
fi

#
# get brand from configured zone
#
ZBRAND=$(/usr/sbin/zoneadm -z "$ZNAME" list -p | awk -F: '{print $6}')

if [ "X$ZBRAND" != "Xbhyve" ]; then
    echo "Removing a CD is only valid for a bhyve zone"
    exit 1
fi

CDFILE=""

#
# work out the name of the cdrom or ISO file from the cdrom attribute
#
CDFILE=$($ZONECFG -z "$ZNAME" info attr name=cdrom | /usr/bin/grep value: | awk '{print $NF}')

if [ -z "${CDFILE}" ]; then
    echo "The $ZNAME zone does not appear to have a cdrom attached"
    exit 1
fi

$ZONECFG -z "$ZNAME" remove attr name=cdrom
$ZONECFG -z "$ZNAME" remove fs dir="$CDFILE" special="$CDFILE"

if [ -n "${REBOOT}" ]; then
    echo "Rebooting $ZNAME"
    $ZONEADM -z "$ZNAME" reboot
else
    echo "Reboot the zone when ready, with:"
    echo "  $ZONEADM -z $ZNAME reboot"
fi
