#!/bin/ksh
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

case $# in
1)
	PKG="$1"
	;;
*)
	exit 1
	;;
esac

#
# short-circuit things that are known package names
#
case $PKG in
    TRIB*|SUNW*)
	echo $PKG
	exit 0
	;;
esac

#
# given an alias, return the package name it corresponds to
#
for repo in `${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos`
do
    if [ -f ${CFGDIR}/repositories/${repo}.aliases ]; then
	FPKG=`/usr/bin/nawk -F'|' '{if ($1 == npkg) print $2}' npkg=${PKG} ${CFGDIR}/repositories/${repo}.aliases`
	if [ -n "$FPKG" ]; then
	    echo "${FPKG}"
	    exit 0
	fi
    fi
done

#
# if we're unable to find an alias, return the original name
#
echo $PKG
