#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-R|-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

for PKG in "$@"
do

#
# short-circuit things that are known package names
#
case $PKG in
    TRIB*|SUNW*)
	echo "$PKG"
	continue
	;;
esac

#
# first time through, get and save the list of available repos
#
if [ -z "$REPOLIST" ]; then
    REPOLIST=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos)
fi

#
# given an alias, return the package name it corresponds to
#
for repo in $REPOLIST
do
    if [ -f "${CFGDIR}/repositories/${repo}.aliases" ]; then
	FPKG=$(/usr/bin/awk -F'|' '{if ($1 == npkg) print $2}' npkg="${PKG}" "${CFGDIR}/repositories/${repo}.aliases")
	if [ -n "$FPKG" ]; then
	    echo "${FPKG}"
	    break
	fi
    fi
done

#
# if we're unable to find an alias, return the original name
#
if [ -z "$FPKG" ]; then
    echo "$PKG"
fi

done
