#!/bin/ksh
#

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${DESTROOT}/${CFGDIR}"
	;;
esac

for PKG in "$@"
do
    
#
# short-circuit things that are known package names
#
case $PKG in
    TRIB*|SUNW*)
	echo "$PKG"
	continue
	;;
esac

#
# first time through, get and save the list of available repos
#
if [ -z "$REPOLIST" ]; then
    REPOLIST=$(${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos)
fi

#
# given an alias, return the package name it corresponds to
#
for repo in $REPOLIST
do
    if [ -f "${CFGDIR}/repositories/${repo}.aliases" ]; then
	FPKG=$(/usr/bin/awk -F'|' '{if ($1 == npkg) print $2}' npkg="${PKG}" "${CFGDIR}/repositories/${repo}.aliases")
	if [ -n "$FPKG" ]; then
	    echo "${FPKG}"
	    break
	fi
    fi
done

#
# if we're unable to find an alias, return the original name
#
if [ -z "$FPKG" ]; then
    echo "$PKG"
fi

done
