#!/bin/ksh
#
# an operating system image retrieval script
#
# used for:
#  - alien zone images
#  - lx zone images
#  - an alien os installer
#
# it will output either the name of the resulting file
# or something containing "ERROR:"
#

ZAPLIBDIR="/usr/lib/zap"
MODE="download"
#
# checksum naming:
# if it's saved as XXX.sha256 then it's a single checksum
# if it's saved as XXX.sha256.txt then it's a list of checksums
#
CKURL=""
CKNAME=""

#
# with -n, just print out the final image name we would store
# with -q, print out the file name iff already downloaded
#
case $1 in
    -n)
	MODE="mapname"
	shift
	;;
    -q)
	MODE="query-download"
	shift
	;;
esac

if [ $# -ne 1 ]; then
    echo "ERROR: Usage: $0 [-n | -q] image_specifier"
    exit 1
fi

IMAGE_DIR=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} image-dir`
USER_AGENT="zap"/`${ZAPLIBDIR}/pkgversion TRIBzap`
ZAP_PROXY=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} proxy`

if [ -n "$ZAP_PROXY" ]; then
    http_proxy=$ZAP_PROXY
    export http_proxy
fi

WCLIENT=/usr/bin/curl
WARGS="-A ${USER_AGENT} -f -s -o"
if [ ! -x $WCLIENT ]; then
    WCLIENT=/usr/bin/wget
    WARGS="-U ${USER_AGENT} -q -O"
fi

#
# we understand several schemes
# - http/https - direct download, gives the full URL
# - distro-name - maps to a well-known url prefix and suffix
#   and the argument is of the form distro-name:version
#
SCHEME=${1%%:*}

case $SCHEME in
    http|https)
	URL="$1"
	DLNAME=${1##*/}
	;;
    omnios|omniosce)
	DLPREFIX="https://downloads.omnios.org/media/"
	DLSUFFIX=".zfs.bz2"
	#
	# we expect a marker of the form r1510XX[y] or bloody
	#
	RELVER=${1#*:}
	#
	# updates have letters on the end as subscripts
	# so pick off the directory name without the subscripts
	#
	case $RELVER in
	    bloody*)
		RELDIR="bloody"
		DLSUFFIX=".zfs.xz"
		;;

	    *)
		RELDIR=${RELVER:0:7}
		;;
	esac
	DLNAME="omnios-${RELVER}${DLSUFFIX}"
	URL="${DLPREFIX}${RELDIR}/${DLNAME}"
	CKURL="${DLPREFIX}${RELDIR}/${DLNAME}.sha256"
	CKNAME="${DLNAME}.sha256"
	;;
    tribblix)
	DLPREFIX="https://pkgs.tribblix.org/iso/"
	DLSUFFIX=".iso"
	TRIBTYPE="tribblix"
	#
	# we expect a marker of the form m##[.#] or m##lx[.#]
	#
	RELVER=${1#*:}
	#
	# allow specification without the leading 0
	#
	case $RELVER in
	    m*)
		RELVER="0${RELVER}"
		;;
	esac
	case $RELVER in
	    *lx*)
		TRIBTYPE="omnitribblix"
		;;
	esac
	DLNAME="${TRIBTYPE}-${RELVER}${DLSUFFIX}"
	URL="${DLPREFIX}/${DLNAME}"
	CKURL="${DLPREFIX}/${DLNAME}.sha256"
	CKNAME="${DLNAME}.sha256"
	;;
    ubuntu)
	#
	# these are the cloud images https://cloud-images.ubuntu.com/
	#
	# syntax expected is 'ubuntu:YY.MM'
	#
	DLPREFIX="https://cloud-images.ubuntu.com/releases/"
	DLSUFFIX=".tar.xz"
	RELVER=${1#*:}
	case $RELVER in
	    lucid)
		RELVER="10.04"
		;;
	    precise)
		RELVER="12.04"
		;;
	    trusty)
		RELVER="14.04"
		;;
	    xenial)
		RELVER="16.04"
		;;
	    bionic)
		RELVER="18.04"
		;;
	    focal)
		RELVER="20.04"
		;;
	    groovy)
		RELVER="20.10"
		;;
	    hirsute)
		RELVER="21.04"
		;;
	esac
	URL="${DLPREFIX}${RELVER}/release/ubuntu-${RELVER}-server-cloudimg-amd64-root${DLSUFFIX}"
	CKURL="${DLPREFIX}${RELVER}/release/SHA256SUMS"
	DLNAME="ubuntu-${RELVER}-server-cloudimg-amd64-root${DLSUFFIX}"
	CKNAME="${DLNAME}.sha256.txt"
	;;
    proxmox)
	#
	# system images come from http://download.proxmox.com/images/system/
	#
	# syntax expected is 'proxmox:distro-version'
	# which we map (manually) to a filename
	#
	# there is no mechanism to handle images which have since been
	# removed from the proxmox site
	#
	# nor is there a mechanism to handle images which have been
	# replaced by newer versions
	#
	DLPREFIX="http://download.proxmox.com/images/system/"
	RELVER=${1#*:}
	case $RELVER in
	    alma|almalinux)
		DLFILE="almalinux-8-default_20210928_amd64.tar.xz"
		DLNAME="proxmox-almalinux-8.tar.xz"
		;;
	    alpine-3.6)
		DLFILE="alpine-3.6-default_20180913_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.6.tar.xz"
		;;
	    alpine-3.7)
		DLFILE="alpine-3.7-default_20180913_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.7.tar.xz"
		;;
	    alpine-3.8|alpine)
		DLFILE="alpine-3.8-default_20180913_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.8.tar.xz"
		;;
	    alpine-3.9)
		DLFILE="alpine-3.9-default_20190224_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.9.tar.xz"
		;;
	    alpine-3.10)
		DLFILE="alpine-3.10-default_20190626_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.10.tar.xz"
		;;
	    alpine-3.11)
		DLFILE="alpine-3.11-default_20200425_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.11.tar.xz"
		;;
	    alpine-3.12)
		DLFILE="alpine-3.12-default_20200823_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.12.tar.xz"
		;;
	    alpine-3.13)
		DLFILE="alpine-3.13-default_20210419_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.13.tar.xz"
		;;
	    alpine-3.14)
		DLFILE="alpine-3.14-default_20210623_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.14.tar.xz"
		;;
	    alpine-3.15)
		DLFILE="alpine-3.15-default_20211202_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.15.tar.xz"
		;;
	    alpine-3.16)
		DLFILE="alpine-3.16-default_20220622_amd64.tar.xz"
		DLNAME="proxmox-alpine-3.16.tar.xz"
		;;
	    arch|archlinux)
		DLFILE="archlinux-base_20211202-1_amd64.tar.gz"
		DLNAME="proxmox-archlinux.tar.gz"
		echo "WARN: arch is not supported by the LX brand"
		;;
	    centos-6)
		DLFILE="centos-6-default_20191016_amd64.tar.xz"
		DLNAME="proxmox-centos-6.tar.xz"
		;;
	    centos-7|centos)
		DLFILE="centos-7-default_20190926_amd64.tar.xz"
		DLNAME="proxmox-centos-7.tar.xz"
		;;
	    centos-8)
		DLFILE="centos-8-default_20201210_amd64.tar.xz"
		DLNAME="proxmox-centos-8.tar.xz"
		;;
	    debian-6)
		DLFILE="debian-6.0-standard_6.0-7_amd64.tar.gz"
		DLNAME="proxmox-debian-6.tar.gz"
		;;
	    debian-7)
		DLFILE="debian-7.0-standard_7.11-1_amd64.tar.gz"
		DLNAME="proxmox-debian-7.tar.gz"
		;;
	    debian-8)
		DLFILE="debian-8.0-standard_8.11-1_amd64.tar.gz"
		DLNAME="proxmox-debian-8.tar.gz"
		;;
	    debian-9|debian)
		DLFILE="debian-9.0-standard_9.7-1_amd64.tar.gz"
		DLNAME="proxmox-debian-9.tar.gz"
		;;
	    debian-10)
		DLFILE="debian-10-standard_10.7-1_amd64.tar.gz"
		DLNAME="proxmox-debian-10.tar.gz"
		;;
	    debian-11)
		DLFILE="debian-11-standard_11.3-1_amd64.tar.gz"
		DLNAME="proxmox-debian-11.tar.gz"
		;;
	    devuan-3)
		DLFILE="devuan-3.0-standard_3.0_amd64.tar.gz"
		DLNAME="proxmox-devuan-3.tar.gz"
		;;
	    devuan|devuan-4)
		DLFILE="devuan-4.0-standard_4.0_amd64.tar.gz"
		DLNAME="proxmox-devuan-4.tar.gz"
		;;
	    fedora-24)
		DLFILE="fedora-24-default_20161207_amd64.tar.xz"
		DLNAME="proxmox-fedora-24.tar.xz"
		;;
	    fedora-25)
		DLFILE="fedora-25-default_20170316_amd64.tar.xz"
		DLNAME="proxmox-fedora-25.tar.xz"
		;;
	    fedora-26)
		DLFILE="fedora-26-default_20171212_amd64.tar.xz"
		DLNAME="proxmox-fedora-26.tar.xz"
		;;
	    fedora-27)
		DLFILE="fedora-27-default_20171212_amd64.tar.xz"
		DLNAME="proxmox-fedora-27.tar.xz"
		;;
	    fedora-28)
		DLFILE="fedora-28-default_20180907_amd64.tar.xz"
		DLNAME="proxmox-fedora-28.tar.xz"
		;;
	    fedora-29|fedora)
		DLFILE="fedora-29-default_20181126_amd64.tar.xz"
		DLNAME="proxmox-fedora-29.tar.xz"
		;;
	    fedora-30)
		DLFILE="fedora-30-default_20190718_amd64.tar.xz"
		DLNAME="proxmox-fedora-30.tar.xz"
		;;
	    fedora-31)
		DLFILE="fedora-31-default_20191029_amd64.tar.xz"
		DLNAME="proxmox-fedora-31.tar.xz"
		;;
	    fedora-32)
		DLFILE="fedora-32-default_20200430_amd64.tar.xz"
		DLNAME="proxmox-fedora-32.tar.xz"
		;;
	    fedora-33)
		DLFILE="fedora-33-default_20201115_amd64.tar.xz"
		DLNAME="proxmox-fedora-33.tar.xz"
		;;
	    fedora-34)
		DLFILE="fedora-34-default_20210427_amd64.tar.xz"
		DLNAME="proxmox-fedora-34.tar.xz"
		;;
	    fedora-35)
		DLFILE="fedora-35-default_20211111_amd64.tar.xz"
		DLNAME="proxmox-fedora-35.tar.xz"
		;;
	    fedora-36)
		DLFILE="fedora-36-default_20220622_amd64.tar.xz"
		DLNAME="proxmox-fedora-36.tar.xz"
		;;
	    gentoo)
		DLFILE="gentoo-current-default_20200310_amd64.tar.xz"
		DLNAME="proxmox-gentoo.tar.xz"
		echo "WARN: gentoo is not supported by the LX brand"
		;;
	    opensuse-42)
		DLFILE="opensuse-42.3-default_20171214_amd64.tar.xz"
		DLNAME="proxmox-opensuse-42.tar.xz"
		;;
	    opensuse-15|opensuse)
		DLFILE="opensuse-15.3-default_20210925_amd64.tar.xz"
		DLNAME="proxmox-opensuse-15.tar.xz"
		;;
	    rocky|rockylinux)
		DLFILE="rockylinux-8-default_20210929_amd64.tar.xz"
		DLNAME="proxmox-rockylinux-8.tar.xz"
		;;
	    ubuntu-*)
		UVER=${RELVER:7:11}
		#
		# LTS releases might have updates
		#
		UUVER=""
		case $UVER in
		    14.04)
			UUVER=".5"
			;;
		    16.04)
			UUVER=".5"
			;;
		    18.04)
			UUVER=".1"
			;;
		esac
		DLFILE="ubuntu-${UVER}-standard_${UVER}${UUVER}-1_amd64.tar.gz"
		DLNAME="proxmox-ubuntu-${UVER}.tar.gz"
		;;
	    ubuntu)
		UVER="18.04"
		UUVER=".1"
		DLFILE="ubuntu-${UVER}-standard_${UVER}${UUVER}-1_amd64.tar.gz"
		DLNAME="proxmox-ubuntu-${UVER}.tar.gz"
		;;
	    *)
		echo "ERROR: Unknown proxmox image"
		exit 2
		;;
	esac
	URL="${DLPREFIX}${DLFILE}"
	;;
    *)
	echo "ERROR: Unrecognized scheme"
	exit 2
	;;
esac

#
# fully qualify the path names
#
FDLNAME=${IMAGE_DIR}/${DLNAME}
if [ -n "$CKNAME" ]; then
    CKNAME=${IMAGE_DIR}/${CKNAME}
fi

case $MODE in
    'mapname')
	echo "$FDLNAME"
	;;
    'query-download')
	if [ -f "$FDLNAME" ]; then
	    echo "$FDLNAME"
	fi
	;;
    'download')
	#
	# get the checksum file first, and exit if that fails
	#
	if [ -n "$CKNAME" ]; then
	    if [ ! -s ${CKNAME} ]; then
		${WCLIENT} ${WARGS} ${CKNAME} ${CKURL}
	    fi
	    if [ ! -f ${CKNAME} ]; then
		echo "ERROR: unable to retrieve checksum file"
		exit 1
	    fi
	    if [ ! -s ${CKNAME} ]; then
		echo "ERROR: checksum file is empty"
		/usr/bin/rm -f ${CKNAME}
		exit 1
	    fi
	fi
	${WCLIENT} ${WARGS} ${FDLNAME} ${URL}
	if [ ! -f ${FDLNAME} ]; then
	    echo "ERROR: download failed"
	    exit 1
	fi
	if [ ! -s ${FDLNAME} ]; then
	    echo "ERROR: download file is empty"
	    /usr/bin/rm -f ${FDLNAME}
	    exit 1
	fi
	if [ -n "$CKNAME" ]; then
	    case $CKNAME in
		*.txt)
		    CKSCHEME=${CKNAME%%.txt}
		    CKSCHEME=${CKSCHEME##*.}
		    CKVAL=`/usr/bin/grep $DLNAME $CKNAME|/usr/bin/tr ' ' '\n'|/usr/bin/grep -v $DLNAME`
		    ;;
		*)
		    CKSCHEME=${CKNAME##*.}
		    CKVAL=`/usr/bin/cat $CKNAME`
		    ;;
	    esac
	    DLVAL=`/usr/bin/openssl $CKSCHEME $FDLNAME | /usr/bin/awk '{print $NF}'`
	    if [ "${DLVAL}" != "${CKVAL}" ]; then
		echo "ERROR: checksum mismatch"
		exit 1
	    fi
	fi
	echo "$FDLNAME"
	;;
esac
