#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# run a zap command in a zone
#
# only supports a subset of the valid zap subcommands - clearly
# the zone-related commands won't work, and should be filtered
# out by the zap wrapper
#
# Usage is:
#   run-in-zone -z zonename subcommand args
# which maps to
#   zlogin zonename zap subcommand args
#

#
# argument processing
#
if [ $# -lt 3 ]; then
   echo "ERROR: insufficient arguments"
   echo "Usage: $0 -z zonename subcommand [args]"
   exit 2
fi
case $1 in
-z)
	ZNAME=$2
	shift
	shift
	SUBCOMMAND=$1
	shift
	;;
*)
	echo "Usage: $0 -z zonename subcommand [args]"
	exit 2
	;;
esac

#
# there are some sanity checks
# * are we in the global zone
# * is the zone running
# * is it a tribblix zone (whole-root or sparse-root)
# * do we have the right privilege to manage it
#
MYZONE=$(/usr/bin/zonename)
if [ "$MYZONE" != "global" ]; then
   echo "ERROR: must be in the global zone"
   exit 1
fi
/usr/sbin/zoneadm -z "$ZNAME" list -p 2>/dev/null | /usr/bin/awk -F: '{print $3, $6}' | read -r zstate ztype
if [ -z "$zstate" ]; then
   echo "ERROR: zone $ZNAME not found"
   exit 1
fi
if [ "X$zstate" != "Xrunning" ]; then
   echo "ERROR: zone must be running, not $zstate"
   exit 1
fi
#
# there are two valid privileges we look for
# "solaris.*" [root]
# "solaris.zone.manage/zonename" [delegated to user]
#
AUTH1=$(/usr/bin/auths|/usr/bin/tr ',' '\n'|/usr/bin/grep -e "solaris.\*" -e "solaris.zone.manage/$ZNAME")
if [ -z "$AUTH1" ]; then
   echo "ERROR: insufficient privileges to manage zone $ZNAME"
   exit 1
fi
case $ztype in
whole-root|sparse-root)
	/usr/bin/pfexec /usr/sbin/zlogin "$ZNAME" /usr/bin/zap "$SUBCOMMAND" "$@"
	;;
*)
	echo "ERROR: unable to manage zones of type $ztype"
	exit 1
esac
