#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

ZAPLIBDIR="/usr/lib/zap"
DESTROOT=""

case $1 in
-R|-C)
	DESTROOT="$2"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
	    echo "ERROR: alternate root $DESTROOT is invalid"
	    exit 1
	fi
	;;
esac

case $# in
1)
	PKG="$1"
	;;
*)
	echo "Usage: zap search [ -R altroot] search_term"
	exit 2
	;;
esac

#
# keep track of packages we have found
# so as not to repeat them
#
typeset -A pmap

#
# simplistic search, start with exact matches on overlays
#
if [ -f "${DESTROOT}/var/sadm/overlays/${PKG}.ovl" ]; then
    if [ -f "${DESTROOT}/var/sadm/overlays/installed/${PKG}" ]; then
	OSTATUS="Installed"
    else
	OSTATUS="Uninstalled"
    fi
    echo "${OSTATUS} overlay ${PKG}"
    grep "^NAME=" "${DESTROOT}/var/sadm/overlays/${PKG}.ovl"
    echo
fi

#
# try and resolve the term to a package alias
#
npkg=$(${ZAPLIBDIR}/resolve-alias "$PKG")
if [ "X${PKG}" != "X${npkg}" ]; then
    echo "$PKG is an alias for $npkg"
fi

#
# look for packages in overlays, this will only identify one overlay
# even if the package is in several overlays, but we will show an
# installed overlay that contains the package if there is one, rather
# than showing an uninstalled overlay which would confuse the user
#
# first pass for installed overlays
#
for match in $(/usr/bin/grep "$PKG" "${DESTROOT}"/var/sadm/overlays/*.pkgs)
do
    OVL=${match%%:*}
    OVL=${OVL##*/}
    OVL=${OVL%.pkgs}
    FPKG=${match##*:}
    if [[ -z ${pmap[$FPKG]} ]]; then
	if [ -d "${DESTROOT}/var/sadm/pkg/${FPKG}" ]; then
	   PSTATUS="Installed"
	else
	   PSTATUS="Uninstalled"
	fi
	if [ -f "${DESTROOT}/var/sadm/overlays/installed/${OVL}" ]; then
	   echo "${PSTATUS} package $FPKG in installed overlay $OVL"
	   pmap[$FPKG]="$PSTATUS"
	fi
    fi
done
#
# second pass for uninstalled overlays
#
for match in $(/usr/bin/grep "$PKG" "${DESTROOT}"/var/sadm/overlays/*.pkgs)
do
    OVL=${match%%:*}
    OVL=${OVL##*/}
    OVL=${OVL%.pkgs}
    FPKG=${match##*:}
    if [[ -z ${pmap[$FPKG]} ]]; then
	if [ -d "${DESTROOT}/var/sadm/pkg/${FPKG}" ]; then
	   PSTATUS="Installed"
	else
	   PSTATUS="Uninstalled"
	fi
	if [ ! -f "${DESTROOT}/var/sadm/overlays/installed/${OVL}" ]; then
	   echo "${PSTATUS} package $FPKG in uninstalled overlay $OVL"
	   pmap[$FPKG]="$PSTATUS"
	fi
    fi
done

#
# then search the catalogs
#
for FPKG in $(awk -F'|' -v pkg="$PKG" '{if ($1 ~ pkg) print $1}' "${DESTROOT}"/etc/zap/repositories/*.catalog)
do
    if [[ -z ${pmap[$FPKG]} ]]; then
	if [ -d "${DESTROOT}/var/sadm/pkg/${FPKG}" ]; then
	   PSTATUS="Installed"
	else
	   PSTATUS="Uninstalled"
	fi
	echo "${PSTATUS} package $FPKG"
	pmap[$FPKG]="$PSTATUS"
    fi
done
