#!/bin/ksh

CFGDIR="/etc/zap"
ZAPLIBDIR="/usr/lib/zap"
DESTROOT=""
PKGARGS=""

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $# in
1)
	PKG="$1"
	;;
*)
	echo "Usage: zap search [ -R altroot] search_term"
	exit 1
	;;
esac

#
# keep track of packages we have found
# so as not to repeat them
#
typeset -A pmap

#
# simplistic search, start with exact matches on overlays
#
if [ -f ${DESTROOT}/var/sadm/overlays/${PKG}.ovl ]; then
    echo "Found a matching overlay"
    ${ZAPLIBDIR}/describe-overlay ${PKGARGS} ${PKG}
fi

#
# try and resolve the term to a package alias
#
npkg=`${ZAPLIBDIR}/resolve-alias $PKG`
if [ "X${PKG}" != "X${npkg}" ]; then
    echo $PKG is an alias for $npkg
fi

#
# look for packages in overlays
#
for match in $(/usr/bin/grep $PKG ${DESTROOT}/var/sadm/overlays/*.pkgs)
do
    OVL=${match%%:*}
    OVL=${OVL##*/}
    OVL=${OVL%.pkgs}
    FPKG=${match##*:}
    if [[ -z ${pmap[$FPKG]} ]]; then
	if [ -f ${DESTROOT}/var/sadm/overlays/installed/$OVL ]; then
	   OSTATUS="installed"
	else
	   OSTATUS="uninstalled"
	fi
	if [ -d ${DESTROOT}/var/sadm/pkg/${FPKG} ]; then
	   PSTATUS="Installed"
	else
	   PSTATUS="Uninstalled"
	fi
	echo ${PSTATUS} package $FPKG in ${OSTATUS} overlay $OVL
	pmap[$FPKG]="$PSTATUS"
    fi
done

#
# then search the catalogs
#
for FPKG in $(awk -F'|' -v pkg=$PKG '{if ($1 ~ pkg) print $1}' ${DESTROOT}/etc/zap/repositories/*.catalog)
do
    if [[ -z ${pmap[$FPKG]} ]]; then
	if [ -d ${DESTROOT}/var/sadm/pkg/${FPKG} ]; then
	   PSTATUS="Installed"
	else
	   PSTATUS="Uninstalled"
	fi
	echo ${PSTATUS} package $FPKG
	pmap[$FPKG]="$PSTATUS"
    fi
done
