#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# set the timezone
#

DESTROOT=""
case $1 in
-C|-R)
	DESTROOT="$2"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $# in
1)
	NEWTZ="$1"
	;;
*)
	echo "Usage: set-timezone timezone"
	exit 2
	;;
esac

#
# sanity check
#
if [ -z "$NEWTZ" ]; then
    echo "ERROR: empty timezone"
    exit 1
fi
if [ ! -f "/usr/share/lib/zoneinfo/${NEWTZ}" ]; then
    echo "ERROR: invalid timezone $NEWTZ"
    exit 1
fi
if [ ! -f "${DESTROOT}/etc/default/init" ]; then
    echo "ERROR: missing init, is that a valid alternate root?"
    exit 1
fi

#
# update /etc/default/init
# if changing the current environment (DESTROOT not set), trigger tzreload
#
sed -i "s:^TZ=\(.*\):TZ=${NEWTZ}:" "${DESTROOT}/etc/default/init"
if [ -z "${DESTROOT}" ]; then
    /usr/sbin/tzreload
fi
