#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2026 Peter Tribble
#

#
# this script may be called as
#   zap unconfigure
# or
#   zap sys-unconfig
# for those with ancient Solaris muscle memory
#
# it will wipe, as far as possible, all configuration and history
# from the system - the resulting image will be blank and ready for
# usage anew
#
# the primary aim of this script is to generate cloud images
#

usage() {
    echo "Usage: $0 [flags]"
    echo "  where possible flags are"
    echo "  -a wipe everything possible"
    echo "  -b clean old boot environments"
    echo "  -j remove the jack user"
    echo "  -z delete all non-global zones"
    echo "  "
    exit 2
}

DOBE=""
DOJACK=""
DOZONES=""

while getopts "abjz" opt; do
case $opt in
a)
    DOBE="y"
    DOJACK="y"
    DOZONES="y"
    ;;
b)
    DOBE="y"
    ;;
j)
    DOJACK="y"
    ;;
z)
    DOZONES="y"
    ;;
*)
    usage
    ;;
esac
done

if [ -n "${DOBE}" ]; then
    echo "Deleting old boot environments"
    for BNAME in $(/usr/sbin/beadm list -H | awk -F';' '{if ($3 != "NR" ) print $1}')
    do
	/usr/sbin/beadm destroy "${BNAME}"
    done
fi
if [ -n "${DOJACK}" ]; then
    echo "Deleting jack user"
    zap delete-user -r jack
fi
if [ -n "${DOZONES}" ]; then
    echo "Deleting non-global zones"
    for ZNAME in $(/usr/sbin/zoneadm list -inc)
    do
	zap destroy-zone -z "${ZNAME}"
    done
fi

#
# the following are always done, this is mostly around tidying up
# and removing unnecessary clutter
#
zap clean-cache -a
passwd -N root
rm /etc/ssh/*key*
rm -fr /root/.ssh
rm /root/.bash_history
rm -f /etc/zap/repositories/*.bak
if [ -f /etc/zap/cache_dir ]; then
    rm -f /etc/zap/cache_dir
fi
if [ -f /etc/zap/image_dir ]; then
    rm -f /etc/zap/image_dir
fi
if [ -f /etc/zap/docker_dir ]; then
    rm -f /etc/zap/docker_dir
fi
if [ -f /etc/zap/proxy_cfg ]; then
    rm -f /etc/zap/proxy_cfg
fi
/usr/bin/find /var/zap/images -type f -exec rm {} \;
# clean all logs
rm -f /var/adm/messages.*
cat /dev/null > /var/adm/messages
cat /dev/null > /var/adm/wtmpx
cat /dev/null > /var/adm/utmpx
cat /dev/null > /var/adm/lastlog
cat /dev/null > /var/adm/loginlog
rm -f /var/log/syslog.*
cat /dev/null > /var/log/syslog
if [ -f /var/log/slim.log ]; then
  cat /dev/null > /var/log/slim.log
fi
if [ -f /var/adm/sulog ]; then
  cat /dev/null > /var/adm/sulog
fi
cat /dev/null > /var/log/authlog
rm -f /var/log/Xorg*
cat /dev/null > /var/cron/log
if [ -f /var/cron/olog ]; then
    rm -f /var/cron/olog
fi
if [ -f /var/adm/spellhist ]; then
    cat /dev/null > /var/adm/spellhist
fi
# and any crash dumps
/usr/bin/find /var/crash -type f -exec rm {} \;
# and any saved core files
/usr/bin/find /var/cores -type f -exec rm {} \;
# and any mailboxes and messages
/usr/bin/find /var/mail -type f -exec rm {} \;
/usr/bin/find /var/spool/mqueue -type f -exec rm {} \;
/usr/bin/find /var/spool/clientmqueue -type f -exec rm {} \;
# any customized CA certificates
if [ -x /usr/lib/zap/manage-cacerts ]; then
    /usr/lib/zap/manage-cacerts clean
fi
# disable automatic updates
if [ -f /var/zap/log/autoupdate.log ]; then
    /usr/bin/zap autoupdate -d
    rm -f /var/zap/log/autoupdate.log
fi

# clean up any customizations
# this will only work in the global zone
rm -f /etc/defaultdomain
PSPOOL="/var/sadm/pkg/SUNWcs/save/pspool/SUNWcs/reloc"
if [ -f ${PSPOOL}/etc/inet/hosts ]; then
    cp ${PSPOOL}/etc/inet/hosts /etc/inet/hosts
    echo "tribblix" > /etc/nodename
fi
if [ -f ${PSPOOL}/etc/inet/networks ]; then
    cp ${PSPOOL}/etc/inet/networks /etc/inet/networks
fi
if [ -f ${PSPOOL}/etc/inet/netmasks ]; then
    cp ${PSPOOL}/etc/inet/netmasks /etc/inet/netmasks
fi
if [ -f ${PSPOOL}/etc/default/init ]; then
    cp ${PSPOOL}/etc/default/init /etc/default/init
fi

# to force device reconfiguration at next boot
touch /reconfigure

sync
sync
