#!/bin/sh
#
# update a package (if necessary)
#
# note that the check isn't that the available version is newer than the
# installed verson, merely that it's different
#
# note also that if called with multiple packages, they are handled
# sequentially and in isolation
#
# note also that until opensxce packages are reversioned for zap, they will
# always show as needing update, so updates are explicitly disabled
#
ZAPLIBDIR="/usr/lib/zap"

case $1 in
-C)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

SRCLIST=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`

#
# prepend the given source to the list, so it gets searched first
#
case $1 in
-s)
	SRCEXTRA="$2"
	SRCARGS="-s ${SRCEXTRA}"
	shift
	shift
	if [ ! -d "$SRCEXTRA" ]; then
	    echo "ERROR: package source $SRCEXTRA doesn't exist"
	    exit 1
	fi
	SRCLIST="$SRCEXTRA $SRCLIST"
	;;
esac

for inpkg in $*
do
    pkg=`${ZAPLIBDIR}/resolve-alias ${CTXARGS} $inpkg`
    /usr/bin/pkginfo ${PKGARGS} -q ${pkg}
    FOUNDPKG=$?
    if [ $FOUNDPKG -ne 0 ]; then
	${ZAPLIBDIR}/install-pkg ${CTXARGS} ${PKGARGS} ${SRCARGS} $pkg
    fi
    IVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
    AFVERSION=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg`
    AVERSION=${AFVERSION% *}
    AREPO=${AFVERSION#* }
    RVERSION=${AVERSION#*.}
    if [ "$AREPO" != "opensxce" ]; then
	if [ "X${pkg}.${IVERSION}" = "X${AVERSION}" ]; then
	    echo "Package $pkg is already at version $IVERSION"
	else
	    echo "Package $pkg is at version $IVERSION and needs updating to $AVERSION"
	    ISINST="false"
	    for SRCDIR in $SRCLIST
	    do
		if [ -f ${SRCDIR}/${AVERSION}.zap ]; then
		    ISINST="true"
		    break
		fi
	    done
	    # download if we don't have it yet
	    if [ "$ISINST" = "false" ]; then
		${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} ${pkg}
	    fi
	    for SRCDIR in $SRCLIST
	    do
		if [ -f ${SRCDIR}/${AVERSION}.zap ]; then
		    ${ZAPLIBDIR}/delpkg ${PKGARGS} $pkg
		    ${ZAPLIBDIR}/instzap ${PKGARGS} ${SRCDIR}/${AVERSION}.zap ${pkg}
		    break
		fi
	    done
	    NVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
	    if [ "X${NVERSION}" = "X${RVERSION}" ]; then
		echo "Update successful."
	    fi
	fi
    fi
done
