#!/bin/sh

ONAME=""
ZAPLIBDIR="/usr/lib/zap"
ODIR="/var/sadm/overlays"
INSTODIR="${ODIR}"
CFGODIR="${ODIR}"
PKGARGS=""
DESTROOT=""
SRCARGS=""

case $1 in
-C)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGODIR="${DESTROOT}/${ODIR}"
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-s)
	SRCDIR="$2"
	SRCARGS="-s ${SRCDIR}"
	shift
	shift
	# FIXME should this be fatal or a warning?
	if [ ! -d "$SRCDIR" ]; then
	    echo "ERROR: package source $SRCDIR doesn't exist"
	    exit 1
	fi
	;;
esac

case $# in
1)
	ONAME="$1"
	;;
*)
	echo "Usage: $0 [-R|-C alt-root] [-s pkg_source] overlay | -a"
	exit 1
	;;
esac

#
# -a means all (installed) overlays
#
case $ONAME in
-a)
	cd ${INSTODIR}/installed
	for novl in *
	do
	    ${ZAPLIBDIR}/update-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
	done
	exit 0
	;;
esac

#
# if not installed, just exit
# if someone has messed with packages behind our back, they suffer
#
if [ ! -f ${INSTODIR}/installed/${ONAME} ]; then
    exit 0
fi

PLIST="${CFGODIR}/${ONAME}.pkgs"
if [ ! -f "${PLIST}" ]; then
    echo "ERROR: package list for overlay ${ONAME} missing"
    exit 1
fi

#
# install dependent overlays, if any
# just in case the overlay dependencies changed
#
OVL="${CFGODIR}/${ONAME}.ovl"
for novl in `/usr/bin/grep '^REQUIRES=' ${OVL} | /usr/bin/sed s:REQUIRES=::`
do
    ${ZAPLIBDIR}/install-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
done

${ZAPLIBDIR}/update-package ${CTXARGS} ${PKGARGS} ${SRCARGS} `cat ${PLIST}`
