#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

ONAME=""
ZAPLIBDIR="/usr/lib/zap"
ODIR="/var/sadm/overlays"
INSTODIR="${ODIR}"
CFGODIR="${ODIR}"
PKGARGS=""
DESTROOT=""
SRCARGS=""

case $1 in
-C)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	CTXARGS="-C ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	CFGODIR="${DESTROOT}/${ODIR}"
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	INSTODIR="${DESTROOT}/${ODIR}"
	;;
esac

case $1 in
-s)
	SRCDIR="$2"
	SRCARGS="-s ${SRCDIR}"
	shift
	shift
	if [ ! -d "$SRCDIR" ]; then
	    echo "WARN: package source $SRCDIR doesn't exist"
	    SRCARGS=""
	fi
	;;
esac

case $# in
1)
	ONAME="$1"
	;;
*)
	echo "Usage: $0 [-R|-C alt-root] [-s pkg_source] overlay | -a"
	exit 1
	;;
esac

#
# -a means all (installed) overlays
#
case $ONAME in
-a)
	cd ${INSTODIR}/installed
	for novl in *
	do
	    ${ZAPLIBDIR}/update-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
	done
	exit 0
	;;
esac

#
# if not installed, just exit
# if someone has messed with packages behind our back, they suffer
#
if [ ! -f ${INSTODIR}/installed/${ONAME} ]; then
    exit 0
fi

PLIST="${CFGODIR}/${ONAME}.pkgs"
if [ ! -f "${PLIST}" ]; then
    echo "ERROR: package list for overlay ${ONAME} missing"
    exit 1
fi

#
# install any new dependent overlays
#
OVL="${CFGODIR}/${ONAME}.ovl"
for novl in $(/usr/bin/awk -F= '{if ($1=="REQUIRES") print $2}' ${OVL})
do
    if [ ! -f ${INSTODIR}/installed/${novl} ]; then
	${ZAPLIBDIR}/install-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
    fi
done

${ZAPLIBDIR}/update-package ${CTXARGS} ${PKGARGS} ${SRCARGS} $(<${PLIST})
