#!/bin/sh
#
# update a package (if necessary)
#
# note that the check isn't that the available version is newer than the
# installed verson, merely that it's different
#
# note also that if called with multiple packages, they are handled
# sequentially and in isolation
#
# note also that until openindiana packages are reversioned for zap, they will
# always show as needing update, so updates are explicitly disabled for oi
#
ZAPLIBDIR="/usr/lib/zap"
CACHE_DIR=`${ZAPLIBDIR}/zap-cfg cache-dir`

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $1 in
-s)
	SRCDIR="$2"
	SRCARGS="-s ${SRCDIR}"
	shift
	shift
	# FIXME should this be fatal or a warning?
	if [ ! -d "$SRCDIR" ]; then
	    echo "ERROR: package source $SRCDIR doesn't exist"
	    exit 1
	fi
	;;
esac

for pkg in $*
do
    IVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
    AFVERSION=`${ZAPLIBDIR}/get-version $pkg`
    AVERSION=${AFVERSION% *}
    AREPO=${AFVERSION#* }
    RVERSION=${AVERSION#*.}
    if [ "$AREPO" != "oi" ]; then
	if [ "X${pkg}.${IVERSION}" = "X${AVERSION}" ]; then
	    echo "Package $pkg is already at version $IVERSION"
	else
	    echo "Package $pkg is at version $IVERSION and needs updating to $AVERSION"
	    if [ ! -f ${CACHE_DIR}/${AVERSION}.zap ]; then
		${ZAPLIBDIR}/retrieve-pkg ${pkg}
	    fi
	    if [ -f ${CACHE_DIR}/${AVERSION}.zap ]; then
		${ZAPLIBDIR}/delpkg ${PKGARGS} $pkg
		${ZAPLIBDIR}/install-pkg ${PKGARGS} ${SRCARGS} $pkg
	    fi
	    NVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
	    if [ "X${NVERSION}" = "X${RVERSION}" ]; then
		echo "Update successful."
	    fi
	fi
    fi
done
