#!/bin/ksh

ZAPLIBDIR="/usr/lib/zap"
PKGARGS=""
DESTROOT=""

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

STATUS=0

#
# then check packages
#
for pkg in `/bin/ls -1 ${DESTROOT}/var/sadm/pkg`
do
      AFVERSION=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg`
      if [ "$AFVERSION" != "$pkg" ]; then
	  AVERSION=${AFVERSION% *}
	  AREPO=${AFVERSION#* }
	  IVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
	  if [ "$AREPO" != "opensxce" ]; then
	      if [ "X${pkg}.${IVERSION}" != "X${AVERSION}" ]; then
		  echo "WARN: package ${pkg} needs updating to ${AVERSION#*.}"
		  STATUS=2
	      fi
	  fi
      else
	  echo "DEBUG: package $pkg not in catalog"
      fi
done

exit $STATUS
