#!/bin/ksh

ZAPLIBDIR="/usr/lib/zap"
PKGARGS=""
DESTROOT=""

case $1 in
-R)
	DESTROOT="$2"
	PKGARGS="-R ${DESTROOT}"
	shift
	shift
	if [ ! -d "$DESTROOT" ]; then
	    echo "ERROR: alternate root $DESTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

STATUS=0

#
# then check packages
#
${ZAPLIBDIR}/get-version ${CTXARGS} `/bin/ls -1 ${DESTROOT}/var/sadm/pkg` | while read AFVERSION
do
    AVERSION=${AFVERSION% *}
    pkg=${AVERSION%%.*}
    if [ "$AFVERSION" != "$pkg" ]; then
	AREPO=${AFVERSION#* }
	IVERSION=`/usr/bin/awk -F= '{if ($1 == "VERSION") print $2}' ${DESTROOT}/var/sadm/pkg/${pkg}/pkginfo`
	if [ "$AREPO" != "opensxce" ]; then
	    if [ "X${pkg}.${IVERSION}" != "X${AVERSION}" ]; then
		echo "WARN: package ${pkg} needs updating to ${AVERSION#*.}"
		STATUS=2
	    fi
	fi
    else
	  echo "DEBUG: package $pkg not in catalog"
    fi
done

exit $STATUS
