#!/bin/ksh
#
# driver for zap
#
ZAPLIBDIR="/usr/lib/zap"

case $# in
0)
	echo "Usage: $0 subcommand [arguments]"
	exit 2
	;;
esac

#
# global context switch comes before the subcommand
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	PKGARGS="-R ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	;;
esac

case $1 in
upgrade)
	shift
	exec ${ZAPLIBDIR}/upgrade $*
	;;
retrieve)
	shift
	exec ${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} $*
	;;
install)
	shift
	exec ${ZAPLIBDIR}/install-pkg ${CTXARGS} $*
	;;
update)
	shift
	exec ${ZAPLIBDIR}/update-package ${CTXARGS} $*
	;;
uninstall)
	shift
	exec ${ZAPLIBDIR}/delpkg ${PKGARGS} $*
	;;
install-overlay)
	shift
	exec ${ZAPLIBDIR}/install-overlay ${CTXARGS} $*
	;;
update-overlay)
	shift
	exec ${ZAPLIBDIR}/update-overlay ${CTXARGS} $*
	;;
uninstall-overlay)
	shift
	exec ${ZAPLIBDIR}/uninstall-overlay $*
	;;
list-overlays)
	shift
	exec ${ZAPLIBDIR}/list-overlays $*
	;;
verify-overlay)
	shift
	exec ${ZAPLIBDIR}/verify-overlay $*
	;;
list-packages)
	shift
	exec /usr/bin/pkginfo ${PKGARGS} $*
	;;
verify-packages)
	shift
	exec ${ZAPLIBDIR}/verify-packages $*
	;;
check-package|pkgchk)
	shift
	exec ${ZAPLIBDIR}/check-package $*
	;;
refresh|refresh-overlays)
	shift
	exec ${ZAPLIBDIR}/refresh-overlays ${CTXARGS} $*
	;;
describe-package)
	shift
	exec /usr/bin/pkginfo ${PKGARGS} -l $*
	;;
describe-overlay)
	shift
	exec ${ZAPLIBDIR}/describe-overlay $*
	;;
refresh-catalog)
	shift
	exec ${ZAPLIBDIR}/refresh-catalog ${CTXARGS} $*
	;;
refresh-filelist)
	shift
	exec ${ZAPLIBDIR}/refresh-filelist ${CTXARGS} $*
	;;
clean-cache)
	shift
	exec ${ZAPLIBDIR}/clean-cache ${CTXARGS} $*
	;;
set-hostname)
	shift
	exec ${ZAPLIBDIR}/set-hostname ${CTXARGS} $*
	;;
create-zone)
	shift
	exec ${ZAPLIBDIR}/create-zone $*
	;;
destroy-zone)
	shift
	exec ${ZAPLIBDIR}/destroy-zone $*
	;;
create-zone-template)
	shift
	exec ${ZAPLIBDIR}/create-zone-template $*
	;;
list-zone-templates)
	shift
	exec ${ZAPLIBDIR}/list-zone-template $*
	;;
destroy-zone-template)
	shift
	exec ${ZAPLIBDIR}/destroy-zone-template $*
	;;
list-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -list $*
	;;
show-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -show $*
	;;
enable-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -enable $*
	;;
disable-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -disable $*
	;;
add-locale)
	shift
	exec ${ZAPLIBDIR}/add-locale ${CTXARGS} $*
	;;
remove-locale)
	shift
	exec ${ZAPLIBDIR}/add-locale ${PKGARGS} -d $*
	;;
create-user)
	shift
	exec ${ZAPLIBDIR}/create-user $*
	;;
delete-user)
	shift
	exec ${ZAPLIBDIR}/delete-user $*
	;;
search)
	shift
	exec ${ZAPLIBDIR}/search $*
	;;
whatprovides)
	shift
	exec ${ZAPLIBDIR}/whatprovides $*
	;;
copy-repo)
	shift
	exec ${ZAPLIBDIR}/copy-repo $*
	;;
help)
	shift
	exec ${ZAPLIBDIR}/zap-help $*
	;;
*)
	echo "Unrecognized subcommand"
	exit 2
	;;
esac
