#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# driver for zap
#
ZAPLIBDIR="/usr/lib/zap"

case $# in
0)
	echo "Usage: $0 subcommand [arguments]"
	exit 2
	;;
esac

#
# global context switch comes before the subcommand
# will force all configuration to be relative to the alternate root
#
# likewise -z to recurse into a zone
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	PKGARGS="-R ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	;;
-z)
	ZNAME=$2
	shift
	shift
	case $1 in
	    *zone*)
		echo "ERROR: cannot run zone commands inside zones"
		exit 1
		;;
	esac
	exec ${ZAPLIBDIR}/run-in-zone -z $ZNAME "$@"
	;;
esac

#
# short names are undocumented
#
case $1 in
upgrade)
	shift
	exec ${ZAPLIBDIR}/upgrade "$@"
	;;
r|get|retrieve)
	shift
	exec ${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} "$@"
	;;
i|ip|add|install)
	shift
	exec ${ZAPLIBDIR}/install-pkg ${CTXARGS} "$@"
	;;
install-recursive)
	shift
	exec ${ZAPLIBDIR}/install-recursive ${CTXARGS} "$@"
	;;
up|update)
	shift
	exec ${ZAPLIBDIR}/update-package ${CTXARGS} "$@"
	;;
d|dp|del|delete|uninstall)
	shift
	exec ${ZAPLIBDIR}/delpkg ${PKGARGS} "$@"
	;;
io|add-overlay|install-overlay)
	shift
	exec ${ZAPLIBDIR}/install-overlay ${CTXARGS} "$@"
	;;
uo|update-overlay)
	shift
	exec ${ZAPLIBDIR}/update-overlay ${CTXARGS} "$@"
	;;
do|delete-overlay|uninstall-overlay)
	shift
	exec ${ZAPLIBDIR}/uninstall-overlay "$@"
	;;
lo|list-overlays)
	shift
	exec ${ZAPLIBDIR}/list-overlays "$@"
	;;
vo|verify-overlay)
	shift
	exec ${ZAPLIBDIR}/verify-overlay "$@"
	;;
lp|list-packages)
	shift
	exec /usr/bin/pkginfo ${PKGARGS} $(${ZAPLIBDIR}/resolve-alias "$@" | sort -u)
	;;
vp|verify-packages)
	shift
	exec ${ZAPLIBDIR}/verify-packages "$@"
	;;
ua|update-all-packages)
	shift
	exec ${ZAPLIBDIR}/verify-packages ${PKGARGS} -u
	;;
check-package|pkgchk)
	shift
	exec ${ZAPLIBDIR}/check-package $(${ZAPLIBDIR}/resolve-alias "$@" | sort -u)
	;;
refresh|refresh-overlays|refresh-catalog)
	shift
	exec ${ZAPLIBDIR}/refresh-overlays ${CTXARGS}
	;;
describe-package)
	shift
	exec /usr/bin/pkginfo ${PKGARGS} -l $(${ZAPLIBDIR}/resolve-alias "$@" | sort -u)
	;;
describe-overlay)
	shift
	exec ${ZAPLIBDIR}/describe-overlay "$@"
	;;
refresh-filelist)
	shift
	exec ${ZAPLIBDIR}/refresh-filelist ${CTXARGS}
	;;
ue|update-everything)
	shift
	${ZAPLIBDIR}/refresh-overlays ${CTXARGS}
	${ZAPLIBDIR}/refresh-filelist ${CTXARGS}
	${ZAPLIBDIR}/update-overlay ${CTXARGS} -a
	exec ${ZAPLIBDIR}/verify-packages ${PKGARGS} -u
	;;
clean-cache)
	shift
	exec ${ZAPLIBDIR}/clean-cache ${CTXARGS} "$@"
	;;
set-hostname)
	shift
	exec ${ZAPLIBDIR}/set-hostname ${CTXARGS} "$@"
	;;
set-timezone)
	shift
	exec ${ZAPLIBDIR}/set-timezone ${CTXARGS} "$@"
	;;
cz|create-zone)
	shift
	exec ${ZAPLIBDIR}/create-zone "$@"
	;;
dz|destroy-zone)
	shift
	exec ${ZAPLIBDIR}/destroy-zone "$@"
	;;
zssh|ssh-zone)
	shift
	exec ${ZAPLIBDIR}/zssh "$@"
	;;
create-zone-template)
	shift
	exec ${ZAPLIBDIR}/create-zone-template "$@"
	;;
list-zone-templates)
	shift
	exec ${ZAPLIBDIR}/list-zone-templates "$@"
	;;
destroy-zone-template)
	shift
	exec ${ZAPLIBDIR}/destroy-zone-template "$@"
	;;
list-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -list "$@"
	;;
show-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -show "$@"
	;;
enable-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -enable "$@"
	;;
disable-services)
	shift
	exec ${ZAPLIBDIR}/zap-service -disable "$@"
	;;
add-locale)
	shift
	exec ${ZAPLIBDIR}/add-locale ${CTXARGS} "$@"
	;;
remove-locale)
	shift
	exec ${ZAPLIBDIR}/add-locale ${PKGARGS} -d "$@"
	;;
installed-locales)
	shift
	exec ${ZAPLIBDIR}/add-locale ${PKGARGS} -i "$@"
	;;
list-locales)
	shift
	exec ${ZAPLIBDIR}/add-locale ${PKGARGS} -l "$@"
	;;
useradd|create-user)
	shift
	exec ${ZAPLIBDIR}/create-user "$@"
	;;
userdel|delete-user)
	shift
	exec ${ZAPLIBDIR}/delete-user "$@"
	;;
search)
	shift
	exec ${ZAPLIBDIR}/search "$@"
	;;
whatprovides)
	shift
	exec ${ZAPLIBDIR}/whatprovides "$@"
	;;
list-package-repos|list-overlay-repos|describe-package-repo|describe-overlay-repo|remove-package-repo|remove-overlay-repo|add-package-repo|add-overlay-repo|modify-package-repo|modify-overlay-repo)
	exec ${ZAPLIBDIR}/manage-repos "$@"
	;;
copy-package-repo)
	shift
	exec ${ZAPLIBDIR}/copy-package-repo "$@"
	;;
copy-overlay-repo)
	shift
	exec ${ZAPLIBDIR}/copy-overlay-repo "$@"
	;;
staticnet)
	shift
	exec ${ZAPLIBDIR}/staticnet-nwam.sh "$@"
	;;
unconfigure|sys-unconfig)
	shift
	exec ${ZAPLIBDIR}/unconfigure "$@"
	;;
remove-cd|remove-cdrom|remove-iso)
	shift
	exec ${ZAPLIBDIR}/remove-cd "$@"
	;;
h|help)
	shift
	exec ${ZAPLIBDIR}/zap-help "$@"
	;;
*)
	echo "Unrecognized subcommand $1"
	exit 2
	;;
esac
