#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# show help for zap
#

HELP_DIR=/usr/share/zap

if [ -z "$PAGER" ]; then
  ZPAGER=$PAGER
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/bin/less
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/xpg4/bin/more
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/bin/more
fi

case $# in
0)
  HELP_FILE=${HELP_DIR}/help.txt
  ;;
*)
  case $1 in
    *-services)
      HELP_FILE=${HELP_DIR}/help.services.txt
      ;;
    remove-locale|installed-locales|list-locales)
      HELP_FILE=${HELP_DIR}/help.add-locale.txt
      ;;
    list-*-repos|describe-*-repo|remove-*-repo|add-*-repo)
      HELP_FILE=${HELP_DIR}/help.manage-repos.txt
      ;;
    delete-user)
      HELP_FILE=${HELP_DIR}/help.create-user.txt
      ;;
    copy-package-repo|copy-overlay-repo)
      HELP_FILE=${HELP_DIR}/help.copy-repo.txt
      ;;
    destroy-zone-template|list-zone-templates)
      HELP_FILE=${HELP_DIR}/help.create-zone-template.txt
      ;;
    *)
      HELP_FILE=${HELP_DIR}/help.${1}.txt
      ;;
    esac
  if [ ! -f "${HELP_FILE}" ]; then
    echo "No specific help for ${1}, showing general help"
    HELP_FILE=${HELP_DIR}/help.txt
  fi
  ;;
esac

exec $ZPAGER "$HELP_FILE"
