#!/bin/ksh
#
# centralized configuration utility for zap
#
# other zap tools should use this script to query and set configuration
#

CFGDIR="/etc/zap"
CACHE_DIR="/var/zap/cache"
IMAGE_DIR="/var/zap/images"
CACHE_CFG="${CFGDIR}/cache_dir"
IMAGE_CFG="${CFGDIR}/image_dir"
PROXY_CFG="${CFGDIR}/proxy_cfg"
SIGN_POLICY="if-signed"
SIGN_CFG="${CFGDIR}/sign_cfg"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	CACHE_DIR="${ALTROOT}/${CACHE_DIR}"
	CACHE_CFG="${CFGDIR}/cache_dir"
	PROXY_CFG="${CFGDIR}/proxy_cfg"
	;;
esac

case $1 in
list-pkg-repos)
	if [ -f ${CFGDIR}/repo.list ]; then
	    #
	    # this is performance sensitive as so many things call it
	    # inline is 30% quicker than sort|awk
	    #
	    typeset -A repos
	    while read n p
	    do
		repos[$p]=$n
	    done < ${CFGDIR}/repo.list
	    while [[ ${#repos[@]} -gt 0 ]]
	    do
		k=(${!repos[@]})
		for j in ${!repos[@]}
		do
		    if [ ${repos[$j]} -lt ${repos[$k]} ]; then
			k=$j
		    fi
		done
		echo $k
		unset repos[$k]
	    done
	fi
	;;
list-overlay-repos)
	if [ -f ${CFGDIR}/overlays.list ]; then
	    #
	    # not quite so performance sensitive
	    # but use the same algorithm anyway
	    #
	    typeset -A repos
	    while read n p
	    do
		repos[$p]=$n
	    done < ${CFGDIR}/overlays.list
	    while [[ ${#repos[@]} -gt 0 ]]
	    do
		k=(${!repos[@]})
		for j in ${!repos[@]}
		do
		    if [ ${repos[$j]} -lt ${repos[$k]} ]; then
			k=$j
		    fi
		done
		echo $k
		unset repos[$k]
	    done
	fi
	;;
repo-url)
	RURL=`/usr/bin/grep '^URL=' ${CFGDIR}/repositories/${2}.repo`
	echo ${RURL/URL=/}
	;;
repo-signer)
	SIGNER=`/usr/bin/grep '^SIGNED=' ${CFGDIR}/repositories/${2}.repo`
	if [[ -n $SIGNER ]]; then
	    echo ${SIGNER/SIGNED=/}
	else
	    echo "no"
	fi
	;;
overlay-url)
	RURL=`/usr/bin/grep '^URL=' ${CFGDIR}/repositories/${2}.ovl`
	echo ${RURL/URL=/}
	;;
cache-dir)
	if [ -f ${CACHE_CFG} ]; then
	    CACHE_DIR=`cat ${CACHE_CFG}`
	fi
	if [ ! -d "${CACHE_DIR}" ]; then
	    /usr/bin/mkdir -p ${CACHE_DIR} 2> /dev/null
	fi
	if [ -d "${CACHE_DIR}" ]; then
	    echo $CACHE_DIR
	else
	    echo "/tmp"
	fi
	;;
image-dir)
	if [ -f ${IMAGE_CFG} ]; then
	    IMAGE_DIR=`cat ${IMAGE_CFG}`
	fi
	if [ ! -d "${IMAGE_DIR}" ]; then
	    /usr/bin/mkdir -p ${IMAGE_DIR} 2> /dev/null
	fi
	if [ -d "${IMAGE_DIR}" ]; then
	    echo $IMAGE_DIR
	else
	    echo "/tmp"
	fi
	;;
sign-policy)
	if [ -f ${SIGN_CFG} ]; then
	    cat ${SIGN_CFG}
	else
	    echo $SIGN_POLICY
	fi
	;;
proxy)
	if [ -f ${PROXY_CFG} ]; then
	    cat ${PROXY_CFG}
	fi
	;;
esac
