#!/bin/ksh
#
# centralized configuration utility for zap
#
# other zap tools should use this script to query and set configuration
#

CFGDIR="/etc/zap"
CACHE_DIR="/var/zap/cache"
CACHE_CFG="${CFGDIR}/cache_dir"
PROXY_CFG="${CFGDIR}/proxy_cfg"
SIGN_POLICY="if-signed"
SIGN_CFG="${CFGDIR}/sign_cfg"

#
# global context switch
# will force all configuration to be relative to the alternate root
#
case $1 in
-C)
	ALTROOT="$2"
	CTXARGS="-C ${ALTROOT}"
	shift
	shift
	if [ ! -d "$ALTROOT" ]; then
	    echo "ERROR: alternate root $ALTROOT doesn't exist"
	    exit 1
	fi
	CFGDIR="${ALTROOT}/${CFGDIR}"
	CACHE_DIR="${ALTROOT}/${CACHE_DIR}"
	CACHE_CFG="${CFGDIR}/cache_dir"
	PROXY_CFG="${CFGDIR}/proxy_cfg"
	;;
esac

case $1 in
list-pkg-repos)
	if [ -f ${CFGDIR}/repo.list ]; then
	    /usr/bin/sort -k1 -n ${CFGDIR}/repo.list | /usr/bin/awk '{print $2}'
	fi
	;;
list-overlay-repos)
	if [ -f ${CFGDIR}/overlays.list ]; then
	    /usr/bin/sort -k1 -n ${CFGDIR}/overlays.list | /usr/bin/awk '{print $2}'
	fi
	;;
repo-url)
	RURL=`/usr/bin/grep '^URL=' ${CFGDIR}/repositories/${2}.repo`
	echo ${RURL/URL=/}
	;;
repo-signer)
	SIGNER=`/usr/bin/grep '^SIGNED=' ${CFGDIR}/repositories/${2}.repo`
	if [[ -n $SIGNER ]]; then
	    echo ${SIGNER/SIGNED=/}
	else
	    echo "no"
	fi
	;;
overlay-url)
	RURL=`/usr/bin/grep '^URL=' ${CFGDIR}/repositories/${2}.ovl`
	echo ${RURL/URL=/}
	;;
cache-dir)
	if [ -f ${CACHE_CFG} ]; then
	    CACHE_DIR=`cat ${CACHE_CFG}`
	fi
	if [ -d "${CACHE_DIR}" ]; then
	    echo $CACHE_DIR
	else
	    echo "/tmp"
	fi
	;;
sign-policy)
	if [ -f ${SIGN_CFG} ]; then
	    cat ${SIGN_CFG}
	else
	    echo $SIGN_POLICY
	fi
	;;
proxy)
	if [ -f ${PROXY_CFG} ]; then
	    cat ${PROXY_CFG}
	fi
	;;
esac
