#!/bin/ksh
#
# show help for zap
#

HELP_DIR=/usr/share/zap

if [ -z "$PAGER" ]; then
  ZPAGER=$PAGER
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/bin/less
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/xpg4/bin/more
fi
if [ ! -x "$ZPAGER" ]; then
  ZPAGER=/usr/bin/more
fi

case $# in
0)
  HELP_FILE=${HELP_DIR}/help.txt
  ;;
*)
  case $1 in
    *-services)
      HELP_FILE=${HELP_DIR}/help.services.txt
      ;;
    remove-locale|installed-locales|list-locales)
      HELP_FILE=${HELP_DIR}/help.add-locale.txt
      ;;
    delete-user)
      HELP_FILE=${HELP_DIR}/help.create-user.txt
      ;;
    *)
      HELP_FILE=${HELP_DIR}/help.${1}.txt
      ;;
    esac
  if [ ! -f ${HELP_FILE} ]; then
    echo "No specific help for ${1}, showing general help"
    HELP_FILE=${HELP_DIR}/help.txt
  fi
  ;;
esac

exec $ZPAGER $HELP_FILE
