#!/bin/ksh
#
# this is the zone configurator
# we are supplied with:
#  the name of the zone, via the -z flag
#  an action and arguments, separated by an = sign
#

ZAPLIBDIR="/usr/lib/zap"
ZNAME=""

usage() {
  echo "Usage: $0 -z zone_name action=arg[=arg...]"
  exit 1
}

while getopts "z:" opt; do
case $opt in
z)
	ZNAME="$OPTARG"
	;;
*)
	usage
	;;
esac
done
shift $((OPTIND - 1))

if [[ -z $ZNAME ]]; then
   echo "ERROR: zone name must be specified"
   usage
fi

case $# in
0)
	usage
	;;
esac

#
# break our argument into action and arguments
#
action=${1%%=*}
args=${1#*=}

if [ -x "${ZAPLIBDIR}/konfigure/$action" ]; then
    exec "${ZAPLIBDIR}/konfigure/$action" -z "${ZNAME}" $args
else
    echo "WARN: unrecognized action $action"
fi
