#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# this is the zone configurator
# we are supplied with:
#  the name of the zone, via the -z flag
#  an action and arguments, separated by an = sign
#

ZAPLIBDIR="/usr/lib/zap"
ZNAME=""

usage() {
  echo "Usage: $0 -z zone_name action=arg[=arg...]"
  exit 2
}

while getopts "z:" opt; do
case $opt in
z)
	ZNAME="$OPTARG"
	;;
*)
	usage
	;;
esac
done
shift $((OPTIND - 1))

if [[ -z $ZNAME ]]; then
   echo "ERROR: zone name must be specified"
   usage
fi

case $# in
0)
	usage
	;;
esac

#
# break our argument into action and arguments
#
action=${1%%=*}
args=${1#*=}

if [ -x "${ZAPLIBDIR}/konfigure/$action" ]; then
    exec "${ZAPLIBDIR}/konfigure/$action" -z "${ZNAME}" $args
else
    echo "WARN: unrecognized action $action"
    exit 2
fi
