.TH "zap" "1" "Sep 25, 2016" "Tribblix"
.SH NAME
zap - Tribblix administration
.SH SYNOPSIS
.LP
.nf
zap subcommand [flags]
.fi
.SH DESCRIPTION
The zap utility is used to manage software packages, zones, and system
upgrades on Tribblix.
.LP
For additional help, issue the command.
.sp
.in +2
.nf
zap help
.fi
.in -2
.sp
.LP
or some subcommands have more specific help, which can be accessed using
.sp
.in +2
.nf
zap help subcommand
.fi
.in -2
.sp
.SH SEE ALSO
.LP
overlays(5)
