.TH "ZAP" "1" "January 10, 2021" "Tribblix"
.SH NAME
zap - Tribblix administration
.SH SYNOPSIS
.nf
\fBzap\fR subcommand [flags]
.fi
.SH DESCRIPTION
The \fBzap\fR utility is used to manage software packages, zones, and system
upgrades on Tribblix.
.LP
For additional help, issue the command.
.sp
.in +2
.nf
\fBzap\fR \fBhelp\fR
.fi
.in -2
.sp
.LP
Some subcommands have more specific help, which can be accessed using
.sp
.in +2
.nf
\fBzap\fR \fBhelp\fR \fIsubcommand\fR
.fi
.in -2
.sp
.SH SEE ALSO
\fBoverlays\fR(5)
